/*
 * SpatioAPI
 *
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio/sdk-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using Spatio.Sdk.Client;
using Spatio.Sdk.Model;

namespace Spatio.Sdk.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IInboxApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Per-bucket unread counts.
        /// </summary>
        /// <exception cref="Spatio.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>InboxCounts</returns>
        InboxCounts GetInboxCounts();

        /// <summary>
        /// Per-bucket unread counts.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Spatio.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of InboxCounts</returns>
        ApiResponse<InboxCounts> GetInboxCountsWithHttpInfo();
        /// <summary>
        /// Unified inbox feed across mail, channel mentions, DMs, system notifications.
        /// </summary>
        /// <exception cref="Spatio.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="category"> (optional)</param>
        /// <param name="unreadOnly"> (optional)</param>
        /// <param name="limit"> (optional)</param>
        /// <returns>InboxListResponse</returns>
        InboxListResponse ListInbox(string? category = default, bool? unreadOnly = default, int? limit = default);

        /// <summary>
        /// Unified inbox feed across mail, channel mentions, DMs, system notifications.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Spatio.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="category"> (optional)</param>
        /// <param name="unreadOnly"> (optional)</param>
        /// <param name="limit"> (optional)</param>
        /// <returns>ApiResponse of InboxListResponse</returns>
        ApiResponse<InboxListResponse> ListInboxWithHttpInfo(string? category = default, bool? unreadOnly = default, int? limit = default);
        /// <summary>
        /// Mark a single inbox item as read.
        /// </summary>
        /// <exception cref="Spatio.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns></returns>
        void MarkInboxItemRead(string id);

        /// <summary>
        /// Mark a single inbox item as read.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Spatio.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> MarkInboxItemReadWithHttpInfo(string id);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Spatio.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="org"></param>
        /// <param name="workspace"></param>
        /// <returns>Dictionary&lt;string, Object&gt;</returns>
        Dictionary<string, Object> WorkspaceGetInboxCounts(string org, string workspace);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Spatio.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="org"></param>
        /// <param name="workspace"></param>
        /// <returns>ApiResponse of Dictionary&lt;string, Object&gt;</returns>
        ApiResponse<Dictionary<string, Object>> WorkspaceGetInboxCountsWithHttpInfo(string org, string workspace);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Spatio.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="org"></param>
        /// <param name="workspace"></param>
        /// <returns>Dictionary&lt;string, Object&gt;</returns>
        Dictionary<string, Object> WorkspaceListInbox(string org, string workspace);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Spatio.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="org"></param>
        /// <param name="workspace"></param>
        /// <returns>ApiResponse of Dictionary&lt;string, Object&gt;</returns>
        ApiResponse<Dictionary<string, Object>> WorkspaceListInboxWithHttpInfo(string org, string workspace);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Spatio.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="org"></param>
        /// <param name="workspace"></param>
        /// <param name="id"></param>
        /// <returns></returns>
        void WorkspaceMarkInboxItemRead(string org, string workspace, string id);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Spatio.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="org"></param>
        /// <param name="workspace"></param>
        /// <param name="id"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> WorkspaceMarkInboxItemReadWithHttpInfo(string org, string workspace, string id);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IInboxApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Per-bucket unread counts.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Spatio.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of InboxCounts</returns>
        System.Threading.Tasks.Task<InboxCounts> GetInboxCountsAsync(System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Per-bucket unread counts.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Spatio.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (InboxCounts)</returns>
        System.Threading.Tasks.Task<ApiResponse<InboxCounts>> GetInboxCountsWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Unified inbox feed across mail, channel mentions, DMs, system notifications.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Spatio.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="category"> (optional)</param>
        /// <param name="unreadOnly"> (optional)</param>
        /// <param name="limit"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of InboxListResponse</returns>
        System.Threading.Tasks.Task<InboxListResponse> ListInboxAsync(string? category = default, bool? unreadOnly = default, int? limit = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Unified inbox feed across mail, channel mentions, DMs, system notifications.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Spatio.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="category"> (optional)</param>
        /// <param name="unreadOnly"> (optional)</param>
        /// <param name="limit"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (InboxListResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<InboxListResponse>> ListInboxWithHttpInfoAsync(string? category = default, bool? unreadOnly = default, int? limit = default, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Mark a single inbox item as read.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Spatio.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task MarkInboxItemReadAsync(string id, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Mark a single inbox item as read.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Spatio.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> MarkInboxItemReadWithHttpInfoAsync(string id, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Spatio.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="org"></param>
        /// <param name="workspace"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Dictionary&lt;string, Object&gt;</returns>
        System.Threading.Tasks.Task<Dictionary<string, Object>> WorkspaceGetInboxCountsAsync(string org, string workspace, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Spatio.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="org"></param>
        /// <param name="workspace"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Dictionary&lt;string, Object&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<Dictionary<string, Object>>> WorkspaceGetInboxCountsWithHttpInfoAsync(string org, string workspace, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Spatio.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="org"></param>
        /// <param name="workspace"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Dictionary&lt;string, Object&gt;</returns>
        System.Threading.Tasks.Task<Dictionary<string, Object>> WorkspaceListInboxAsync(string org, string workspace, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Spatio.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="org"></param>
        /// <param name="workspace"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Dictionary&lt;string, Object&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<Dictionary<string, Object>>> WorkspaceListInboxWithHttpInfoAsync(string org, string workspace, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Spatio.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="org"></param>
        /// <param name="workspace"></param>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task WorkspaceMarkInboxItemReadAsync(string org, string workspace, string id, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Spatio.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="org"></param>
        /// <param name="workspace"></param>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> WorkspaceMarkInboxItemReadWithHttpInfoAsync(string org, string workspace, string id, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IInboxApi : IInboxApiSync, IInboxApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class InboxApi : IDisposable, IInboxApi
    {
        private Spatio.Sdk.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="InboxApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public InboxApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="InboxApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public InboxApi(string basePath)
        {
            this.Configuration = Spatio.Sdk.Client.Configuration.MergeConfigurations(
                Spatio.Sdk.Client.GlobalConfiguration.Instance,
                new Spatio.Sdk.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Spatio.Sdk.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Spatio.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="InboxApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public InboxApi(Spatio.Sdk.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Spatio.Sdk.Client.Configuration.MergeConfigurations(
                Spatio.Sdk.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Spatio.Sdk.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Spatio.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="InboxApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public InboxApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="InboxApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public InboxApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Spatio.Sdk.Client.Configuration.MergeConfigurations(
                Spatio.Sdk.Client.GlobalConfiguration.Instance,
                new Spatio.Sdk.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Spatio.Sdk.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Spatio.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="InboxApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public InboxApi(HttpClient client, Spatio.Sdk.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Spatio.Sdk.Client.Configuration.MergeConfigurations(
                Spatio.Sdk.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Spatio.Sdk.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Spatio.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="InboxApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public InboxApi(Spatio.Sdk.Client.ISynchronousClient client, Spatio.Sdk.Client.IAsynchronousClient asyncClient, Spatio.Sdk.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Spatio.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public Spatio.Sdk.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Spatio.Sdk.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Spatio.Sdk.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Spatio.Sdk.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Spatio.Sdk.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Per-bucket unread counts. 
        /// </summary>
        /// <exception cref="Spatio.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>InboxCounts</returns>
        public InboxCounts GetInboxCounts()
        {
            Spatio.Sdk.Client.ApiResponse<InboxCounts> localVarResponse = GetInboxCountsWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// Per-bucket unread counts. 
        /// </summary>
        /// <exception cref="Spatio.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of InboxCounts</returns>
        public Spatio.Sdk.Client.ApiResponse<InboxCounts> GetInboxCountsWithHttpInfo()
        {
            Spatio.Sdk.Client.RequestOptions localVarRequestOptions = new Spatio.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Spatio.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Spatio.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<InboxCounts>("/v1/inbox/counts", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetInboxCounts", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Per-bucket unread counts. 
        /// </summary>
        /// <exception cref="Spatio.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of InboxCounts</returns>
        public async System.Threading.Tasks.Task<InboxCounts> GetInboxCountsAsync(System.Threading.CancellationToken cancellationToken = default)
        {
            Spatio.Sdk.Client.ApiResponse<InboxCounts> localVarResponse = await GetInboxCountsWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Per-bucket unread counts. 
        /// </summary>
        /// <exception cref="Spatio.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (InboxCounts)</returns>
        public async System.Threading.Tasks.Task<Spatio.Sdk.Client.ApiResponse<InboxCounts>> GetInboxCountsWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default)
        {

            Spatio.Sdk.Client.RequestOptions localVarRequestOptions = new Spatio.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Spatio.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Spatio.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<InboxCounts>("/v1/inbox/counts", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetInboxCounts", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Unified inbox feed across mail, channel mentions, DMs, system notifications. 
        /// </summary>
        /// <exception cref="Spatio.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="category"> (optional)</param>
        /// <param name="unreadOnly"> (optional)</param>
        /// <param name="limit"> (optional)</param>
        /// <returns>InboxListResponse</returns>
        public InboxListResponse ListInbox(string? category = default, bool? unreadOnly = default, int? limit = default)
        {
            Spatio.Sdk.Client.ApiResponse<InboxListResponse> localVarResponse = ListInboxWithHttpInfo(category, unreadOnly, limit);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Unified inbox feed across mail, channel mentions, DMs, system notifications. 
        /// </summary>
        /// <exception cref="Spatio.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="category"> (optional)</param>
        /// <param name="unreadOnly"> (optional)</param>
        /// <param name="limit"> (optional)</param>
        /// <returns>ApiResponse of InboxListResponse</returns>
        public Spatio.Sdk.Client.ApiResponse<InboxListResponse> ListInboxWithHttpInfo(string? category = default, bool? unreadOnly = default, int? limit = default)
        {
            Spatio.Sdk.Client.RequestOptions localVarRequestOptions = new Spatio.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Spatio.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Spatio.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (category != null)
            {
                localVarRequestOptions.QueryParameters.Add(Spatio.Sdk.Client.ClientUtils.ParameterToMultiMap("", "category", category));
            }
            if (unreadOnly != null)
            {
                localVarRequestOptions.QueryParameters.Add(Spatio.Sdk.Client.ClientUtils.ParameterToMultiMap("", "unreadOnly", unreadOnly));
            }
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(Spatio.Sdk.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<InboxListResponse>("/v1/inbox", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListInbox", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Unified inbox feed across mail, channel mentions, DMs, system notifications. 
        /// </summary>
        /// <exception cref="Spatio.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="category"> (optional)</param>
        /// <param name="unreadOnly"> (optional)</param>
        /// <param name="limit"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of InboxListResponse</returns>
        public async System.Threading.Tasks.Task<InboxListResponse> ListInboxAsync(string? category = default, bool? unreadOnly = default, int? limit = default, System.Threading.CancellationToken cancellationToken = default)
        {
            Spatio.Sdk.Client.ApiResponse<InboxListResponse> localVarResponse = await ListInboxWithHttpInfoAsync(category, unreadOnly, limit, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Unified inbox feed across mail, channel mentions, DMs, system notifications. 
        /// </summary>
        /// <exception cref="Spatio.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="category"> (optional)</param>
        /// <param name="unreadOnly"> (optional)</param>
        /// <param name="limit"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (InboxListResponse)</returns>
        public async System.Threading.Tasks.Task<Spatio.Sdk.Client.ApiResponse<InboxListResponse>> ListInboxWithHttpInfoAsync(string? category = default, bool? unreadOnly = default, int? limit = default, System.Threading.CancellationToken cancellationToken = default)
        {

            Spatio.Sdk.Client.RequestOptions localVarRequestOptions = new Spatio.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Spatio.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Spatio.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (category != null)
            {
                localVarRequestOptions.QueryParameters.Add(Spatio.Sdk.Client.ClientUtils.ParameterToMultiMap("", "category", category));
            }
            if (unreadOnly != null)
            {
                localVarRequestOptions.QueryParameters.Add(Spatio.Sdk.Client.ClientUtils.ParameterToMultiMap("", "unreadOnly", unreadOnly));
            }
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(Spatio.Sdk.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<InboxListResponse>("/v1/inbox", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListInbox", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Mark a single inbox item as read. 
        /// </summary>
        /// <exception cref="Spatio.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns></returns>
        public void MarkInboxItemRead(string id)
        {
            MarkInboxItemReadWithHttpInfo(id);
        }

        /// <summary>
        /// Mark a single inbox item as read. 
        /// </summary>
        /// <exception cref="Spatio.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        public Spatio.Sdk.Client.ApiResponse<Object> MarkInboxItemReadWithHttpInfo(string id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new Spatio.Sdk.Client.ApiException(400, "Missing required parameter 'id' when calling InboxApi->MarkInboxItemRead");

            Spatio.Sdk.Client.RequestOptions localVarRequestOptions = new Spatio.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Spatio.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Spatio.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", Spatio.Sdk.Client.ClientUtils.ParameterToString(id)); // path parameter

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Patch<Object>("/v1/inbox/{id}/read", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("MarkInboxItemRead", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Mark a single inbox item as read. 
        /// </summary>
        /// <exception cref="Spatio.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task MarkInboxItemReadAsync(string id, System.Threading.CancellationToken cancellationToken = default)
        {
            await MarkInboxItemReadWithHttpInfoAsync(id, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// Mark a single inbox item as read. 
        /// </summary>
        /// <exception cref="Spatio.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Spatio.Sdk.Client.ApiResponse<Object>> MarkInboxItemReadWithHttpInfoAsync(string id, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new Spatio.Sdk.Client.ApiException(400, "Missing required parameter 'id' when calling InboxApi->MarkInboxItemRead");


            Spatio.Sdk.Client.RequestOptions localVarRequestOptions = new Spatio.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Spatio.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Spatio.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", Spatio.Sdk.Client.ClientUtils.ParameterToString(id)); // path parameter

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PatchAsync<Object>("/v1/inbox/{id}/read", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("MarkInboxItemRead", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Spatio.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="org"></param>
        /// <param name="workspace"></param>
        /// <returns>Dictionary&lt;string, Object&gt;</returns>
        public Dictionary<string, Object> WorkspaceGetInboxCounts(string org, string workspace)
        {
            Spatio.Sdk.Client.ApiResponse<Dictionary<string, Object>> localVarResponse = WorkspaceGetInboxCountsWithHttpInfo(org, workspace);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Spatio.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="org"></param>
        /// <param name="workspace"></param>
        /// <returns>ApiResponse of Dictionary&lt;string, Object&gt;</returns>
        public Spatio.Sdk.Client.ApiResponse<Dictionary<string, Object>> WorkspaceGetInboxCountsWithHttpInfo(string org, string workspace)
        {
            // verify the required parameter 'org' is set
            if (org == null)
                throw new Spatio.Sdk.Client.ApiException(400, "Missing required parameter 'org' when calling InboxApi->WorkspaceGetInboxCounts");

            // verify the required parameter 'workspace' is set
            if (workspace == null)
                throw new Spatio.Sdk.Client.ApiException(400, "Missing required parameter 'workspace' when calling InboxApi->WorkspaceGetInboxCounts");

            Spatio.Sdk.Client.RequestOptions localVarRequestOptions = new Spatio.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Spatio.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Spatio.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("org", Spatio.Sdk.Client.ClientUtils.ParameterToString(org)); // path parameter
            localVarRequestOptions.PathParameters.Add("workspace", Spatio.Sdk.Client.ClientUtils.ParameterToString(workspace)); // path parameter

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<Dictionary<string, Object>>("/v1/organizations/{org}/workspaces/{workspace}/inbox/counts", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("WorkspaceGetInboxCounts", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Spatio.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="org"></param>
        /// <param name="workspace"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Dictionary&lt;string, Object&gt;</returns>
        public async System.Threading.Tasks.Task<Dictionary<string, Object>> WorkspaceGetInboxCountsAsync(string org, string workspace, System.Threading.CancellationToken cancellationToken = default)
        {
            Spatio.Sdk.Client.ApiResponse<Dictionary<string, Object>> localVarResponse = await WorkspaceGetInboxCountsWithHttpInfoAsync(org, workspace, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Spatio.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="org"></param>
        /// <param name="workspace"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Dictionary&lt;string, Object&gt;)</returns>
        public async System.Threading.Tasks.Task<Spatio.Sdk.Client.ApiResponse<Dictionary<string, Object>>> WorkspaceGetInboxCountsWithHttpInfoAsync(string org, string workspace, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'org' is set
            if (org == null)
                throw new Spatio.Sdk.Client.ApiException(400, "Missing required parameter 'org' when calling InboxApi->WorkspaceGetInboxCounts");

            // verify the required parameter 'workspace' is set
            if (workspace == null)
                throw new Spatio.Sdk.Client.ApiException(400, "Missing required parameter 'workspace' when calling InboxApi->WorkspaceGetInboxCounts");


            Spatio.Sdk.Client.RequestOptions localVarRequestOptions = new Spatio.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Spatio.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Spatio.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("org", Spatio.Sdk.Client.ClientUtils.ParameterToString(org)); // path parameter
            localVarRequestOptions.PathParameters.Add("workspace", Spatio.Sdk.Client.ClientUtils.ParameterToString(workspace)); // path parameter

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<Dictionary<string, Object>>("/v1/organizations/{org}/workspaces/{workspace}/inbox/counts", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("WorkspaceGetInboxCounts", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Spatio.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="org"></param>
        /// <param name="workspace"></param>
        /// <returns>Dictionary&lt;string, Object&gt;</returns>
        public Dictionary<string, Object> WorkspaceListInbox(string org, string workspace)
        {
            Spatio.Sdk.Client.ApiResponse<Dictionary<string, Object>> localVarResponse = WorkspaceListInboxWithHttpInfo(org, workspace);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Spatio.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="org"></param>
        /// <param name="workspace"></param>
        /// <returns>ApiResponse of Dictionary&lt;string, Object&gt;</returns>
        public Spatio.Sdk.Client.ApiResponse<Dictionary<string, Object>> WorkspaceListInboxWithHttpInfo(string org, string workspace)
        {
            // verify the required parameter 'org' is set
            if (org == null)
                throw new Spatio.Sdk.Client.ApiException(400, "Missing required parameter 'org' when calling InboxApi->WorkspaceListInbox");

            // verify the required parameter 'workspace' is set
            if (workspace == null)
                throw new Spatio.Sdk.Client.ApiException(400, "Missing required parameter 'workspace' when calling InboxApi->WorkspaceListInbox");

            Spatio.Sdk.Client.RequestOptions localVarRequestOptions = new Spatio.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Spatio.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Spatio.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("org", Spatio.Sdk.Client.ClientUtils.ParameterToString(org)); // path parameter
            localVarRequestOptions.PathParameters.Add("workspace", Spatio.Sdk.Client.ClientUtils.ParameterToString(workspace)); // path parameter

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<Dictionary<string, Object>>("/v1/organizations/{org}/workspaces/{workspace}/inbox", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("WorkspaceListInbox", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Spatio.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="org"></param>
        /// <param name="workspace"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Dictionary&lt;string, Object&gt;</returns>
        public async System.Threading.Tasks.Task<Dictionary<string, Object>> WorkspaceListInboxAsync(string org, string workspace, System.Threading.CancellationToken cancellationToken = default)
        {
            Spatio.Sdk.Client.ApiResponse<Dictionary<string, Object>> localVarResponse = await WorkspaceListInboxWithHttpInfoAsync(org, workspace, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Spatio.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="org"></param>
        /// <param name="workspace"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Dictionary&lt;string, Object&gt;)</returns>
        public async System.Threading.Tasks.Task<Spatio.Sdk.Client.ApiResponse<Dictionary<string, Object>>> WorkspaceListInboxWithHttpInfoAsync(string org, string workspace, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'org' is set
            if (org == null)
                throw new Spatio.Sdk.Client.ApiException(400, "Missing required parameter 'org' when calling InboxApi->WorkspaceListInbox");

            // verify the required parameter 'workspace' is set
            if (workspace == null)
                throw new Spatio.Sdk.Client.ApiException(400, "Missing required parameter 'workspace' when calling InboxApi->WorkspaceListInbox");


            Spatio.Sdk.Client.RequestOptions localVarRequestOptions = new Spatio.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Spatio.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Spatio.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("org", Spatio.Sdk.Client.ClientUtils.ParameterToString(org)); // path parameter
            localVarRequestOptions.PathParameters.Add("workspace", Spatio.Sdk.Client.ClientUtils.ParameterToString(workspace)); // path parameter

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<Dictionary<string, Object>>("/v1/organizations/{org}/workspaces/{workspace}/inbox", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("WorkspaceListInbox", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Spatio.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="org"></param>
        /// <param name="workspace"></param>
        /// <param name="id"></param>
        /// <returns></returns>
        public void WorkspaceMarkInboxItemRead(string org, string workspace, string id)
        {
            WorkspaceMarkInboxItemReadWithHttpInfo(org, workspace, id);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Spatio.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="org"></param>
        /// <param name="workspace"></param>
        /// <param name="id"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        public Spatio.Sdk.Client.ApiResponse<Object> WorkspaceMarkInboxItemReadWithHttpInfo(string org, string workspace, string id)
        {
            // verify the required parameter 'org' is set
            if (org == null)
                throw new Spatio.Sdk.Client.ApiException(400, "Missing required parameter 'org' when calling InboxApi->WorkspaceMarkInboxItemRead");

            // verify the required parameter 'workspace' is set
            if (workspace == null)
                throw new Spatio.Sdk.Client.ApiException(400, "Missing required parameter 'workspace' when calling InboxApi->WorkspaceMarkInboxItemRead");

            // verify the required parameter 'id' is set
            if (id == null)
                throw new Spatio.Sdk.Client.ApiException(400, "Missing required parameter 'id' when calling InboxApi->WorkspaceMarkInboxItemRead");

            Spatio.Sdk.Client.RequestOptions localVarRequestOptions = new Spatio.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Spatio.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Spatio.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("org", Spatio.Sdk.Client.ClientUtils.ParameterToString(org)); // path parameter
            localVarRequestOptions.PathParameters.Add("workspace", Spatio.Sdk.Client.ClientUtils.ParameterToString(workspace)); // path parameter
            localVarRequestOptions.PathParameters.Add("id", Spatio.Sdk.Client.ClientUtils.ParameterToString(id)); // path parameter

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Patch<Object>("/v1/organizations/{org}/workspaces/{workspace}/inbox/{id}/read", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("WorkspaceMarkInboxItemRead", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Spatio.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="org"></param>
        /// <param name="workspace"></param>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task WorkspaceMarkInboxItemReadAsync(string org, string workspace, string id, System.Threading.CancellationToken cancellationToken = default)
        {
            await WorkspaceMarkInboxItemReadWithHttpInfoAsync(org, workspace, id, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Spatio.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="org"></param>
        /// <param name="workspace"></param>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Spatio.Sdk.Client.ApiResponse<Object>> WorkspaceMarkInboxItemReadWithHttpInfoAsync(string org, string workspace, string id, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'org' is set
            if (org == null)
                throw new Spatio.Sdk.Client.ApiException(400, "Missing required parameter 'org' when calling InboxApi->WorkspaceMarkInboxItemRead");

            // verify the required parameter 'workspace' is set
            if (workspace == null)
                throw new Spatio.Sdk.Client.ApiException(400, "Missing required parameter 'workspace' when calling InboxApi->WorkspaceMarkInboxItemRead");

            // verify the required parameter 'id' is set
            if (id == null)
                throw new Spatio.Sdk.Client.ApiException(400, "Missing required parameter 'id' when calling InboxApi->WorkspaceMarkInboxItemRead");


            Spatio.Sdk.Client.RequestOptions localVarRequestOptions = new Spatio.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Spatio.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Spatio.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("org", Spatio.Sdk.Client.ClientUtils.ParameterToString(org)); // path parameter
            localVarRequestOptions.PathParameters.Add("workspace", Spatio.Sdk.Client.ClientUtils.ParameterToString(workspace)); // path parameter
            localVarRequestOptions.PathParameters.Add("id", Spatio.Sdk.Client.ClientUtils.ParameterToString(id)); // path parameter

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PatchAsync<Object>("/v1/organizations/{org}/workspaces/{workspace}/inbox/{id}/read", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("WorkspaceMarkInboxItemRead", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
