/*
 * SpatioAPI
 *
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio/sdk-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Spatio.Sdk.Client.FileParameter;
using OpenAPIDateConverter = Spatio.Sdk.Client.OpenAPIDateConverter;

namespace Spatio.Sdk.Model
{
    /// <summary>
    /// Attendee
    /// </summary>
    [DataContract(Name = "Attendee")]
    public partial class Attendee : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public AttendeeStatus Status { get; set; }

        /// <summary>
        /// Gets or Sets Role
        /// </summary>
        [DataMember(Name = "role", IsRequired = true, EmitDefaultValue = true)]
        public AttendeeRole Role { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="Attendee" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Attendee() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Attendee" /> class.
        /// </summary>
        /// <param name="email">email (required).</param>
        /// <param name="name">name.</param>
        /// <param name="status">status (required).</param>
        /// <param name="role">role (required).</param>
        /// <param name="optional">Legacy boolean — superseded by &#x60;role&#x60; (&#x60;role: optional&#x60; carries the same signal). Kept on the wire for client compatibility.  (required).</param>
        /// <param name="comment">comment.</param>
        /// <param name="additionalGuests">additionalGuests.</param>
        public Attendee(string email = default, string name = default, AttendeeStatus status = default, AttendeeRole role = default, bool optional = default, string comment = default, int additionalGuests = default)
        {
            // to ensure "email" is required (not null)
            if (email == null)
            {
                throw new ArgumentNullException("email is a required property for Attendee and cannot be null");
            }
            this.Email = email;
            this.Status = status;
            this.Role = role;
            this.Optional = optional;
            this.Name = name;
            this.Comment = comment;
            this.AdditionalGuests = additionalGuests;
        }

        /// <summary>
        /// Gets or Sets Email
        /// </summary>
        [DataMember(Name = "email", IsRequired = true, EmitDefaultValue = true)]
        public string Email { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Legacy boolean — superseded by &#x60;role&#x60; (&#x60;role: optional&#x60; carries the same signal). Kept on the wire for client compatibility. 
        /// </summary>
        /// <value>Legacy boolean — superseded by &#x60;role&#x60; (&#x60;role: optional&#x60; carries the same signal). Kept on the wire for client compatibility. </value>
        [DataMember(Name = "optional", IsRequired = true, EmitDefaultValue = true)]
        public bool Optional { get; set; }

        /// <summary>
        /// Gets or Sets Comment
        /// </summary>
        [DataMember(Name = "comment", EmitDefaultValue = false)]
        public string Comment { get; set; }

        /// <summary>
        /// Gets or Sets AdditionalGuests
        /// </summary>
        [DataMember(Name = "additional_guests", EmitDefaultValue = false)]
        public int AdditionalGuests { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Attendee {\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Role: ").Append(Role).Append("\n");
            sb.Append("  Optional: ").Append(Optional).Append("\n");
            sb.Append("  Comment: ").Append(Comment).Append("\n");
            sb.Append("  AdditionalGuests: ").Append(AdditionalGuests).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
