/*
 * SpatioAPI
 *
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio-labs/spatio-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Spatio.Sdk.Client.FileParameter;
using OpenAPIDateConverter = Spatio.Sdk.Client.OpenAPIDateConverter;

namespace Spatio.Sdk.Model
{
    /// <summary>
    /// Type-specific payload for a block. Fields populated depend on &#x60;Block.type&#x60;. All fields are optional at the schema level; the runtime enforces the per-type contract.  Note: this object uses snake_case keys to match the JSON the Go &#x60;providers.BlockContent&#x60; struct emits and accepts. Other parts of the SpatioAPI use camelCase; blocks are the exception because the block model is shared with external Notion-like providers whose canonical wire format is snake_case. 
    /// </summary>
    [DataContract(Name = "BlockContent")]
    public partial class BlockContent : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BlockContent" /> class.
        /// </summary>
        /// <param name="richText">richText.</param>
        /// <param name="language">Programming language for &#x60;code&#x60; blocks..</param>
        /// <param name="varChecked">Toggle state for &#x60;to_do&#x60; blocks..</param>
        /// <param name="icon">Emoji or short string for &#x60;callout&#x60; blocks..</param>
        /// <param name="color">Theme color for &#x60;callout&#x60; blocks..</param>
        /// <param name="url">Source URL for &#x60;image&#x60;, &#x60;video&#x60;, &#x60;file&#x60; blocks..</param>
        /// <param name="caption">Visible caption for media blocks..</param>
        /// <param name="altText">Screen-reader description for media blocks. Distinct from &#x60;caption&#x60; (visible to readers) — required for accessible notes when the image conveys meaning. .</param>
        /// <param name="embedUrl">Source URL for &#x60;embed&#x60; blocks..</param>
        /// <param name="cells">2D rich-text grid for &#x60;table&#x60; and &#x60;table_row&#x60; blocks..</param>
        /// <param name="expression">TeX/MathJax expression for &#x60;equation&#x60; blocks..</param>
        public BlockContent(List<RichTextObject> richText = default, string language = default, bool varChecked = default, string icon = default, string color = default, string url = default, string caption = default, string altText = default, string embedUrl = default, List<List<RichTextObject>> cells = default, string expression = default)
        {
            this.RichText = richText;
            this.Language = language;
            this.Checked = varChecked;
            this.Icon = icon;
            this.Color = color;
            this.Url = url;
            this.Caption = caption;
            this.AltText = altText;
            this.EmbedUrl = embedUrl;
            this.Cells = cells;
            this.Expression = expression;
        }

        /// <summary>
        /// Gets or Sets RichText
        /// </summary>
        [DataMember(Name = "rich_text", EmitDefaultValue = false)]
        public List<RichTextObject> RichText { get; set; }

        /// <summary>
        /// Programming language for &#x60;code&#x60; blocks.
        /// </summary>
        /// <value>Programming language for &#x60;code&#x60; blocks.</value>
        [DataMember(Name = "language", EmitDefaultValue = false)]
        public string Language { get; set; }

        /// <summary>
        /// Toggle state for &#x60;to_do&#x60; blocks.
        /// </summary>
        /// <value>Toggle state for &#x60;to_do&#x60; blocks.</value>
        [DataMember(Name = "checked", EmitDefaultValue = true)]
        public bool Checked { get; set; }

        /// <summary>
        /// Emoji or short string for &#x60;callout&#x60; blocks.
        /// </summary>
        /// <value>Emoji or short string for &#x60;callout&#x60; blocks.</value>
        [DataMember(Name = "icon", EmitDefaultValue = false)]
        public string Icon { get; set; }

        /// <summary>
        /// Theme color for &#x60;callout&#x60; blocks.
        /// </summary>
        /// <value>Theme color for &#x60;callout&#x60; blocks.</value>
        [DataMember(Name = "color", EmitDefaultValue = false)]
        public string Color { get; set; }

        /// <summary>
        /// Source URL for &#x60;image&#x60;, &#x60;video&#x60;, &#x60;file&#x60; blocks.
        /// </summary>
        /// <value>Source URL for &#x60;image&#x60;, &#x60;video&#x60;, &#x60;file&#x60; blocks.</value>
        [DataMember(Name = "url", EmitDefaultValue = false)]
        public string Url { get; set; }

        /// <summary>
        /// Visible caption for media blocks.
        /// </summary>
        /// <value>Visible caption for media blocks.</value>
        [DataMember(Name = "caption", EmitDefaultValue = false)]
        public string Caption { get; set; }

        /// <summary>
        /// Screen-reader description for media blocks. Distinct from &#x60;caption&#x60; (visible to readers) — required for accessible notes when the image conveys meaning. 
        /// </summary>
        /// <value>Screen-reader description for media blocks. Distinct from &#x60;caption&#x60; (visible to readers) — required for accessible notes when the image conveys meaning. </value>
        [DataMember(Name = "alt_text", EmitDefaultValue = false)]
        public string AltText { get; set; }

        /// <summary>
        /// Source URL for &#x60;embed&#x60; blocks.
        /// </summary>
        /// <value>Source URL for &#x60;embed&#x60; blocks.</value>
        [DataMember(Name = "embed_url", EmitDefaultValue = false)]
        public string EmbedUrl { get; set; }

        /// <summary>
        /// 2D rich-text grid for &#x60;table&#x60; and &#x60;table_row&#x60; blocks.
        /// </summary>
        /// <value>2D rich-text grid for &#x60;table&#x60; and &#x60;table_row&#x60; blocks.</value>
        [DataMember(Name = "cells", EmitDefaultValue = false)]
        public List<List<RichTextObject>> Cells { get; set; }

        /// <summary>
        /// TeX/MathJax expression for &#x60;equation&#x60; blocks.
        /// </summary>
        /// <value>TeX/MathJax expression for &#x60;equation&#x60; blocks.</value>
        [DataMember(Name = "expression", EmitDefaultValue = false)]
        public string Expression { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BlockContent {\n");
            sb.Append("  RichText: ").Append(RichText).Append("\n");
            sb.Append("  Language: ").Append(Language).Append("\n");
            sb.Append("  Checked: ").Append(Checked).Append("\n");
            sb.Append("  Icon: ").Append(Icon).Append("\n");
            sb.Append("  Color: ").Append(Color).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  Caption: ").Append(Caption).Append("\n");
            sb.Append("  AltText: ").Append(AltText).Append("\n");
            sb.Append("  EmbedUrl: ").Append(EmbedUrl).Append("\n");
            sb.Append("  Cells: ").Append(Cells).Append("\n");
            sb.Append("  Expression: ").Append(Expression).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
