/*
 * SpatioAPI
 *
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio-labs/spatio-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Spatio.Sdk.Client.FileParameter;
using OpenAPIDateConverter = Spatio.Sdk.Client.OpenAPIDateConverter;

namespace Spatio.Sdk.Model
{
    /// <summary>
    /// Partial-success envelope for bulk delete/move.
    /// </summary>
    [DataContract(Name = "BulkFilesResponse")]
    public partial class BulkFilesResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BulkFilesResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected BulkFilesResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="BulkFilesResponse" /> class.
        /// </summary>
        /// <param name="success">success (required).</param>
        /// <param name="affectedCount">affectedCount (required).</param>
        /// <param name="fileIds">fileIds (required).</param>
        /// <param name="failed">failed (required).</param>
        public BulkFilesResponse(bool success = default, int affectedCount = default, List<string> fileIds = default, List<BulkFilesResponseFailedInner> failed = default)
        {
            this.Success = success;
            this.AffectedCount = affectedCount;
            // to ensure "fileIds" is required (not null)
            if (fileIds == null)
            {
                throw new ArgumentNullException("fileIds is a required property for BulkFilesResponse and cannot be null");
            }
            this.FileIds = fileIds;
            // to ensure "failed" is required (not null)
            if (failed == null)
            {
                throw new ArgumentNullException("failed is a required property for BulkFilesResponse and cannot be null");
            }
            this.Failed = failed;
        }

        /// <summary>
        /// Gets or Sets Success
        /// </summary>
        [DataMember(Name = "success", IsRequired = true, EmitDefaultValue = true)]
        public bool Success { get; set; }

        /// <summary>
        /// Gets or Sets AffectedCount
        /// </summary>
        [DataMember(Name = "affectedCount", IsRequired = true, EmitDefaultValue = true)]
        public int AffectedCount { get; set; }

        /// <summary>
        /// Gets or Sets FileIds
        /// </summary>
        [DataMember(Name = "fileIds", IsRequired = true, EmitDefaultValue = true)]
        public List<string> FileIds { get; set; }

        /// <summary>
        /// Gets or Sets Failed
        /// </summary>
        [DataMember(Name = "failed", IsRequired = true, EmitDefaultValue = true)]
        public List<BulkFilesResponseFailedInner> Failed { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BulkFilesResponse {\n");
            sb.Append("  Success: ").Append(Success).Append("\n");
            sb.Append("  AffectedCount: ").Append(AffectedCount).Append("\n");
            sb.Append("  FileIds: ").Append(FileIds).Append("\n");
            sb.Append("  Failed: ").Append(Failed).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
