/*
 * SpatioAPI
 *
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio/sdk-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Spatio.Sdk.Client.FileParameter;
using OpenAPIDateConverter = Spatio.Sdk.Client.OpenAPIDateConverter;

namespace Spatio.Sdk.Model
{
    /// <summary>
    /// BulkUpdateTasksResponse
    /// </summary>
    [DataContract(Name = "BulkUpdateTasksResponse")]
    public partial class BulkUpdateTasksResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BulkUpdateTasksResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected BulkUpdateTasksResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="BulkUpdateTasksResponse" /> class.
        /// </summary>
        /// <param name="success">success (required).</param>
        /// <param name="affectedCount">affectedCount (required).</param>
        /// <param name="tasks">tasks (required).</param>
        /// <param name="failed">failed (required).</param>
        public BulkUpdateTasksResponse(bool success = default, int affectedCount = default, List<Task> tasks = default, List<BulkDeleteTasksResponseFailedInner> failed = default)
        {
            this.Success = success;
            this.AffectedCount = affectedCount;
            // to ensure "tasks" is required (not null)
            if (tasks == null)
            {
                throw new ArgumentNullException("tasks is a required property for BulkUpdateTasksResponse and cannot be null");
            }
            this.Tasks = tasks;
            // to ensure "failed" is required (not null)
            if (failed == null)
            {
                throw new ArgumentNullException("failed is a required property for BulkUpdateTasksResponse and cannot be null");
            }
            this.Failed = failed;
        }

        /// <summary>
        /// Gets or Sets Success
        /// </summary>
        [DataMember(Name = "success", IsRequired = true, EmitDefaultValue = true)]
        public bool Success { get; set; }

        /// <summary>
        /// Gets or Sets AffectedCount
        /// </summary>
        [DataMember(Name = "affectedCount", IsRequired = true, EmitDefaultValue = true)]
        public int AffectedCount { get; set; }

        /// <summary>
        /// Gets or Sets Tasks
        /// </summary>
        [DataMember(Name = "tasks", IsRequired = true, EmitDefaultValue = true)]
        public List<Task> Tasks { get; set; }

        /// <summary>
        /// Gets or Sets Failed
        /// </summary>
        [DataMember(Name = "failed", IsRequired = true, EmitDefaultValue = true)]
        public List<BulkDeleteTasksResponseFailedInner> Failed { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BulkUpdateTasksResponse {\n");
            sb.Append("  Success: ").Append(Success).Append("\n");
            sb.Append("  AffectedCount: ").Append(AffectedCount).Append("\n");
            sb.Append("  Tasks: ").Append(Tasks).Append("\n");
            sb.Append("  Failed: ").Append(Failed).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
