/*
 * SpatioAPI
 *
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio-labs/spatio-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Spatio.Sdk.Client.FileParameter;
using OpenAPIDateConverter = Spatio.Sdk.Client.OpenAPIDateConverter;

namespace Spatio.Sdk.Model
{
    /// <summary>
    /// Partial-success envelope for &#x60;bulkMarkEmailsRead&#x60;. &#x60;updated&#x60; is a count (not an array — distinct from archive/delete which return the actual id list). The failed-row shape uses &#x60;id&#x60; (also distinct — renderer-compat legacy). 
    /// </summary>
    [DataContract(Name = "BulkMarkReadResponse")]
    public partial class BulkMarkReadResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BulkMarkReadResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected BulkMarkReadResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="BulkMarkReadResponse" /> class.
        /// </summary>
        /// <param name="updated">Number of messages successfully marked. (required).</param>
        /// <param name="failed">failed (required).</param>
        public BulkMarkReadResponse(int updated = default, List<BulkMarkReadResponseFailedInner> failed = default)
        {
            this.Updated = updated;
            // to ensure "failed" is required (not null)
            if (failed == null)
            {
                throw new ArgumentNullException("failed is a required property for BulkMarkReadResponse and cannot be null");
            }
            this.Failed = failed;
        }

        /// <summary>
        /// Number of messages successfully marked.
        /// </summary>
        /// <value>Number of messages successfully marked.</value>
        [DataMember(Name = "updated", IsRequired = true, EmitDefaultValue = true)]
        public int Updated { get; set; }

        /// <summary>
        /// Gets or Sets Failed
        /// </summary>
        [DataMember(Name = "failed", IsRequired = true, EmitDefaultValue = true)]
        public List<BulkMarkReadResponseFailedInner> Failed { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BulkMarkReadResponse {\n");
            sb.Append("  Updated: ").Append(Updated).Append("\n");
            sb.Append("  Failed: ").Append(Failed).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
