/*
 * SpatioAPI
 *
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio-labs/spatio-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Spatio.Sdk.Client.FileParameter;
using OpenAPIDateConverter = Spatio.Sdk.Client.OpenAPIDateConverter;

namespace Spatio.Sdk.Model
{
    /// <summary>
    /// Either populate &#x60;taskIds&#x60; (with optional parallel &#x60;accountIds&#x60;) for multi-task delete, or &#x60;taskId&#x60; (with optional &#x60;accountId&#x60;) for the single-task fallback. &#x60;taskIds&#x60; wins when both are set. 
    /// </summary>
    [DataContract(Name = "BulkDeleteTasksRequest")]
    public partial class BulkDeleteTasksRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BulkDeleteTasksRequest" /> class.
        /// </summary>
        /// <param name="taskIds">taskIds.</param>
        /// <param name="accountIds">Parallel slice with taskIds — accountIds[i] targets taskIds[i]..</param>
        /// <param name="taskId">Singular fallback when only deleting one task..</param>
        /// <param name="accountId">accountId.</param>
        public BulkDeleteTasksRequest(List<string> taskIds = default, List<string> accountIds = default, string taskId = default, string accountId = default)
        {
            this.TaskIds = taskIds;
            this.AccountIds = accountIds;
            this.TaskId = taskId;
            this.AccountId = accountId;
        }

        /// <summary>
        /// Gets or Sets TaskIds
        /// </summary>
        [DataMember(Name = "taskIds", EmitDefaultValue = false)]
        public List<string> TaskIds { get; set; }

        /// <summary>
        /// Parallel slice with taskIds — accountIds[i] targets taskIds[i].
        /// </summary>
        /// <value>Parallel slice with taskIds — accountIds[i] targets taskIds[i].</value>
        [DataMember(Name = "accountIds", EmitDefaultValue = false)]
        public List<string> AccountIds { get; set; }

        /// <summary>
        /// Singular fallback when only deleting one task.
        /// </summary>
        /// <value>Singular fallback when only deleting one task.</value>
        [DataMember(Name = "taskId", EmitDefaultValue = false)]
        public string TaskId { get; set; }

        /// <summary>
        /// Gets or Sets AccountId
        /// </summary>
        [DataMember(Name = "accountId", EmitDefaultValue = false)]
        public string AccountId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BulkDeleteTasksRequest {\n");
            sb.Append("  TaskIds: ").Append(TaskIds).Append("\n");
            sb.Append("  AccountIds: ").Append(AccountIds).Append("\n");
            sb.Append("  TaskId: ").Append(TaskId).Append("\n");
            sb.Append("  AccountId: ").Append(AccountId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
