/*
 * SpatioAPI
 *
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio-labs/spatio-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Spatio.Sdk.Client.FileParameter;
using OpenAPIDateConverter = Spatio.Sdk.Client.OpenAPIDateConverter;

namespace Spatio.Sdk.Model
{
    /// <summary>
    /// CreateOrganizationRequest
    /// </summary>
    [DataContract(Name = "CreateOrganizationRequest")]
    public partial class CreateOrganizationRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateOrganizationRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateOrganizationRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateOrganizationRequest" /> class.
        /// </summary>
        /// <param name="name">name (required).</param>
        /// <param name="slug">Auto-generated from &#x60;name&#x60; if omitted. Slug collisions are auto-suffixed with &#x60;-2&#x60;, &#x60;-3&#x60;, etc. .</param>
        /// <param name="description">description.</param>
        /// <param name="logoUrl">logoUrl.</param>
        /// <param name="createDefaultWorkspace">&#x60;true&#x60; (default) creates a default workspace alongside the org..</param>
        /// <param name="defaultWorkspaceName">defaultWorkspaceName.</param>
        public CreateOrganizationRequest(string name = default, string slug = default, string description = default, string logoUrl = default, bool createDefaultWorkspace = default, string defaultWorkspaceName = default)
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for CreateOrganizationRequest and cannot be null");
            }
            this.Name = name;
            this.Slug = slug;
            this.Description = description;
            this.LogoUrl = logoUrl;
            this.CreateDefaultWorkspace = createDefaultWorkspace;
            this.DefaultWorkspaceName = defaultWorkspaceName;
        }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Auto-generated from &#x60;name&#x60; if omitted. Slug collisions are auto-suffixed with &#x60;-2&#x60;, &#x60;-3&#x60;, etc. 
        /// </summary>
        /// <value>Auto-generated from &#x60;name&#x60; if omitted. Slug collisions are auto-suffixed with &#x60;-2&#x60;, &#x60;-3&#x60;, etc. </value>
        [DataMember(Name = "slug", EmitDefaultValue = false)]
        public string Slug { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name = "description", EmitDefaultValue = false)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets LogoUrl
        /// </summary>
        [DataMember(Name = "logoUrl", EmitDefaultValue = false)]
        public string LogoUrl { get; set; }

        /// <summary>
        /// &#x60;true&#x60; (default) creates a default workspace alongside the org.
        /// </summary>
        /// <value>&#x60;true&#x60; (default) creates a default workspace alongside the org.</value>
        [DataMember(Name = "createDefaultWorkspace", EmitDefaultValue = true)]
        public bool CreateDefaultWorkspace { get; set; }

        /// <summary>
        /// Gets or Sets DefaultWorkspaceName
        /// </summary>
        [DataMember(Name = "defaultWorkspaceName", EmitDefaultValue = false)]
        public string DefaultWorkspaceName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateOrganizationRequest {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Slug: ").Append(Slug).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  LogoUrl: ").Append(LogoUrl).Append("\n");
            sb.Append("  CreateDefaultWorkspace: ").Append(CreateDefaultWorkspace).Append("\n");
            sb.Append("  DefaultWorkspaceName: ").Append(DefaultWorkspaceName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
