/*
 * SpatioAPI
 *
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio/sdk-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Spatio.Sdk.Client.FileParameter;
using OpenAPIDateConverter = Spatio.Sdk.Client.OpenAPIDateConverter;

namespace Spatio.Sdk.Model
{
    /// <summary>
    /// CreateRecordTypeRequest
    /// </summary>
    [DataContract(Name = "CreateRecordTypeRequest")]
    public partial class CreateRecordTypeRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateRecordTypeRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateRecordTypeRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateRecordTypeRequest" /> class.
        /// </summary>
        /// <param name="organizationId">organizationId.</param>
        /// <param name="slug">slug.</param>
        /// <param name="name">name (required).</param>
        /// <param name="namePlural">namePlural.</param>
        /// <param name="icon">icon.</param>
        /// <param name="attributeSchema">attributeSchema.</param>
        public CreateRecordTypeRequest(string organizationId = default, string slug = default, string name = default, string namePlural = default, string icon = default, List<Dictionary<string, Object>> attributeSchema = default)
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for CreateRecordTypeRequest and cannot be null");
            }
            this.Name = name;
            this.OrganizationId = organizationId;
            this.Slug = slug;
            this.NamePlural = namePlural;
            this.Icon = icon;
            this.AttributeSchema = attributeSchema;
        }

        /// <summary>
        /// Gets or Sets OrganizationId
        /// </summary>
        [DataMember(Name = "organization_id", EmitDefaultValue = false)]
        public string OrganizationId { get; set; }

        /// <summary>
        /// Gets or Sets Slug
        /// </summary>
        [DataMember(Name = "slug", EmitDefaultValue = false)]
        public string Slug { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets NamePlural
        /// </summary>
        [DataMember(Name = "name_plural", EmitDefaultValue = false)]
        public string NamePlural { get; set; }

        /// <summary>
        /// Gets or Sets Icon
        /// </summary>
        [DataMember(Name = "icon", EmitDefaultValue = false)]
        public string Icon { get; set; }

        /// <summary>
        /// Gets or Sets AttributeSchema
        /// </summary>
        [DataMember(Name = "attribute_schema", EmitDefaultValue = false)]
        public List<Dictionary<string, Object>> AttributeSchema { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateRecordTypeRequest {\n");
            sb.Append("  OrganizationId: ").Append(OrganizationId).Append("\n");
            sb.Append("  Slug: ").Append(Slug).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  NamePlural: ").Append(NamePlural).Append("\n");
            sb.Append("  Icon: ").Append(Icon).Append("\n");
            sb.Append("  AttributeSchema: ").Append(AttributeSchema).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
