/*
 * SpatioAPI
 *
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio/sdk-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Spatio.Sdk.Client.FileParameter;
using OpenAPIDateConverter = Spatio.Sdk.Client.OpenAPIDateConverter;
using System.Reflection;

namespace Spatio.Sdk.Model
{
    /// <summary>
    /// CreateNote400Response
    /// </summary>
    [JsonConverter(typeof(CreateNote400ResponseJsonConverter))]
    [DataContract(Name = "createNote_400_response")]
    public partial class CreateNote400Response : AbstractOpenAPISchema, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateNote400Response" /> class
        /// with the <see cref="ApiError" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of ApiError.</param>
        public CreateNote400Response(ApiError actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CreateNote400Response" /> class
        /// with the <see cref="AmbiguousAccountError" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of AmbiguousAccountError.</param>
        public CreateNote400Response(AmbiguousAccountError actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(AmbiguousAccountError) || value is AmbiguousAccountError)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(ApiError) || value is ApiError)
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: AmbiguousAccountError, ApiError");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `ApiError`. If the actual instance is not `ApiError`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of ApiError</returns>
        public ApiError GetApiError()
        {
            return (ApiError)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `AmbiguousAccountError`. If the actual instance is not `AmbiguousAccountError`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of AmbiguousAccountError</returns>
        public AmbiguousAccountError GetAmbiguousAccountError()
        {
            return (AmbiguousAccountError)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreateNote400Response {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, CreateNote400Response.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of CreateNote400Response
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of CreateNote400Response</returns>
        public static CreateNote400Response FromJson(string jsonString)
        {
            CreateNote400Response newCreateNote400Response = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newCreateNote400Response;
            }
            int match = 0;
            List<string> matchedTypes = new List<string>();

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(AmbiguousAccountError).GetProperty("AdditionalProperties") == null)
                {
                    newCreateNote400Response = new CreateNote400Response(JsonConvert.DeserializeObject<AmbiguousAccountError>(jsonString, CreateNote400Response.SerializerSettings));
                }
                else
                {
                    newCreateNote400Response = new CreateNote400Response(JsonConvert.DeserializeObject<AmbiguousAccountError>(jsonString, CreateNote400Response.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("AmbiguousAccountError");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into AmbiguousAccountError: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(ApiError).GetProperty("AdditionalProperties") == null)
                {
                    newCreateNote400Response = new CreateNote400Response(JsonConvert.DeserializeObject<ApiError>(jsonString, CreateNote400Response.SerializerSettings));
                }
                else
                {
                    newCreateNote400Response = new CreateNote400Response(JsonConvert.DeserializeObject<ApiError>(jsonString, CreateNote400Response.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("ApiError");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into ApiError: {1}", jsonString, exception.ToString()));
            }

            if (match == 0)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
            }
            else if (match > 1)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` incorrectly matches more than one schema (should be exactly one match): " + String.Join(",", matchedTypes));
            }

            // deserialization is considered successful at this point if no exception has been thrown.
            return newCreateNote400Response;
        }


        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// Custom JSON converter for CreateNote400Response
    /// </summary>
    public class CreateNote400ResponseJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(CreateNote400Response).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            switch(reader.TokenType) 
            {
                case JsonToken.StartObject:
                    return CreateNote400Response.FromJson(JObject.Load(reader).ToString(Formatting.None));
                case JsonToken.StartArray:
                    return CreateNote400Response.FromJson(JArray.Load(reader).ToString(Formatting.None));
                default:
                    return null;
            }
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
