/*
 * SpatioAPI
 *
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio-labs/spatio-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Spatio.Sdk.Client.FileParameter;
using OpenAPIDateConverter = Spatio.Sdk.Client.OpenAPIDateConverter;

namespace Spatio.Sdk.Model
{
    /// <summary>
    /// Forward to either a DM (&#x60;toDmId&#x60;) or a channel (&#x60;toChannelId&#x60;); exactly one required.
    /// </summary>
    [DataContract(Name = "DMForwardRequest")]
    public partial class DMForwardRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DMForwardRequest" /> class.
        /// </summary>
        /// <param name="toDmId">toDmId.</param>
        /// <param name="toChannelId">toChannelId.</param>
        /// <param name="accountId">accountId.</param>
        public DMForwardRequest(string toDmId = default, string toChannelId = default, string accountId = default)
        {
            this.ToDmId = toDmId;
            this.ToChannelId = toChannelId;
            this.AccountId = accountId;
        }

        /// <summary>
        /// Gets or Sets ToDmId
        /// </summary>
        [DataMember(Name = "toDmId", EmitDefaultValue = false)]
        public string ToDmId { get; set; }

        /// <summary>
        /// Gets or Sets ToChannelId
        /// </summary>
        [DataMember(Name = "toChannelId", EmitDefaultValue = false)]
        public string ToChannelId { get; set; }

        /// <summary>
        /// Gets or Sets AccountId
        /// </summary>
        [DataMember(Name = "accountId", EmitDefaultValue = false)]
        public string AccountId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DMForwardRequest {\n");
            sb.Append("  ToDmId: ").Append(ToDmId).Append("\n");
            sb.Append("  ToChannelId: ").Append(ToChannelId).Append("\n");
            sb.Append("  AccountId: ").Append(AccountId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
