/*
 * SpatioAPI
 *
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio/sdk-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Spatio.Sdk.Client.FileParameter;
using OpenAPIDateConverter = Spatio.Sdk.Client.OpenAPIDateConverter;

namespace Spatio.Sdk.Model
{
    /// <summary>
    /// InitChunkedUploadRequest
    /// </summary>
    [DataContract(Name = "InitChunkedUploadRequest")]
    public partial class InitChunkedUploadRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InitChunkedUploadRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected InitChunkedUploadRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="InitChunkedUploadRequest" /> class.
        /// </summary>
        /// <param name="fileName">fileName (required).</param>
        /// <param name="totalSize">totalSize (required).</param>
        /// <param name="mimeType">mimeType (required).</param>
        /// <param name="expectedBlocks">Hashes of every block the client intends to upload. (required).</param>
        /// <param name="folderId">folderId.</param>
        /// <param name="workspaceId">workspaceId.</param>
        /// <param name="organizationId">organizationId.</param>
        public InitChunkedUploadRequest(string fileName = default, long totalSize = default, string mimeType = default, List<string> expectedBlocks = default, string folderId = default, string workspaceId = default, string organizationId = default)
        {
            // to ensure "fileName" is required (not null)
            if (fileName == null)
            {
                throw new ArgumentNullException("fileName is a required property for InitChunkedUploadRequest and cannot be null");
            }
            this.FileName = fileName;
            this.TotalSize = totalSize;
            // to ensure "mimeType" is required (not null)
            if (mimeType == null)
            {
                throw new ArgumentNullException("mimeType is a required property for InitChunkedUploadRequest and cannot be null");
            }
            this.MimeType = mimeType;
            // to ensure "expectedBlocks" is required (not null)
            if (expectedBlocks == null)
            {
                throw new ArgumentNullException("expectedBlocks is a required property for InitChunkedUploadRequest and cannot be null");
            }
            this.ExpectedBlocks = expectedBlocks;
            this.FolderId = folderId;
            this.WorkspaceId = workspaceId;
            this.OrganizationId = organizationId;
        }

        /// <summary>
        /// Gets or Sets FileName
        /// </summary>
        [DataMember(Name = "fileName", IsRequired = true, EmitDefaultValue = true)]
        public string FileName { get; set; }

        /// <summary>
        /// Gets or Sets TotalSize
        /// </summary>
        [DataMember(Name = "totalSize", IsRequired = true, EmitDefaultValue = true)]
        public long TotalSize { get; set; }

        /// <summary>
        /// Gets or Sets MimeType
        /// </summary>
        [DataMember(Name = "mimeType", IsRequired = true, EmitDefaultValue = true)]
        public string MimeType { get; set; }

        /// <summary>
        /// Hashes of every block the client intends to upload.
        /// </summary>
        /// <value>Hashes of every block the client intends to upload.</value>
        [DataMember(Name = "expectedBlocks", IsRequired = true, EmitDefaultValue = true)]
        public List<string> ExpectedBlocks { get; set; }

        /// <summary>
        /// Gets or Sets FolderId
        /// </summary>
        [DataMember(Name = "folderId", EmitDefaultValue = true)]
        public string FolderId { get; set; }

        /// <summary>
        /// Gets or Sets WorkspaceId
        /// </summary>
        [DataMember(Name = "workspaceId", EmitDefaultValue = false)]
        public string WorkspaceId { get; set; }

        /// <summary>
        /// Gets or Sets OrganizationId
        /// </summary>
        [DataMember(Name = "organizationId", EmitDefaultValue = false)]
        public string OrganizationId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InitChunkedUploadRequest {\n");
            sb.Append("  FileName: ").Append(FileName).Append("\n");
            sb.Append("  TotalSize: ").Append(TotalSize).Append("\n");
            sb.Append("  MimeType: ").Append(MimeType).Append("\n");
            sb.Append("  ExpectedBlocks: ").Append(ExpectedBlocks).Append("\n");
            sb.Append("  FolderId: ").Append(FolderId).Append("\n");
            sb.Append("  WorkspaceId: ").Append(WorkspaceId).Append("\n");
            sb.Append("  OrganizationId: ").Append(OrganizationId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
