/*
 * SpatioAPI
 *
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio-labs/spatio-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Spatio.Sdk.Client.FileParameter;
using OpenAPIDateConverter = Spatio.Sdk.Client.OpenAPIDateConverter;

namespace Spatio.Sdk.Model
{
    /// <summary>
    /// IssueCollaborationTokenRequest
    /// </summary>
    [DataContract(Name = "issueCollaborationToken_request")]
    public partial class IssueCollaborationTokenRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="IssueCollaborationTokenRequest" /> class.
        /// </summary>
        /// <param name="room">Optional &#x60;&lt;type&gt;:&lt;id&gt;&#x60; room identifier (e.g. &#x60;note:abc123&#x60;). When set, the JWT only authorizes this single room. .</param>
        public IssueCollaborationTokenRequest(string room = default)
        {
            this.Room = room;
        }

        /// <summary>
        /// Optional &#x60;&lt;type&gt;:&lt;id&gt;&#x60; room identifier (e.g. &#x60;note:abc123&#x60;). When set, the JWT only authorizes this single room. 
        /// </summary>
        /// <value>Optional &#x60;&lt;type&gt;:&lt;id&gt;&#x60; room identifier (e.g. &#x60;note:abc123&#x60;). When set, the JWT only authorizes this single room. </value>
        /*
        <example>note:abc123</example>
        */
        [DataMember(Name = "room", EmitDefaultValue = false)]
        public string Room { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class IssueCollaborationTokenRequest {\n");
            sb.Append("  Room: ").Append(Room).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
