/*
 * SpatioAPI
 *
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio/sdk-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Spatio.Sdk.Client.FileParameter;
using OpenAPIDateConverter = Spatio.Sdk.Client.OpenAPIDateConverter;

namespace Spatio.Sdk.Model
{
    /// <summary>
    /// A single JSON Web Key (RFC 7517 §4) — RSA public key.
    /// </summary>
    [DataContract(Name = "JWK")]
    public partial class JWK : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="JWK" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected JWK() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="JWK" /> class.
        /// </summary>
        /// <param name="kty">kty (required).</param>
        /// <param name="use">use (required).</param>
        /// <param name="alg">alg (required).</param>
        /// <param name="kid">kid (required).</param>
        /// <param name="n">Base64url-encoded RSA modulus. (required).</param>
        /// <param name="e">Base64url-encoded RSA exponent. Almost always \&quot;AQAB\&quot;. (required).</param>
        public JWK(string kty = default, string use = default, string alg = default, string kid = default, string n = default, string e = default)
        {
            // to ensure "kty" is required (not null)
            if (kty == null)
            {
                throw new ArgumentNullException("kty is a required property for JWK and cannot be null");
            }
            this.Kty = kty;
            // to ensure "use" is required (not null)
            if (use == null)
            {
                throw new ArgumentNullException("use is a required property for JWK and cannot be null");
            }
            this.Use = use;
            // to ensure "alg" is required (not null)
            if (alg == null)
            {
                throw new ArgumentNullException("alg is a required property for JWK and cannot be null");
            }
            this.Alg = alg;
            // to ensure "kid" is required (not null)
            if (kid == null)
            {
                throw new ArgumentNullException("kid is a required property for JWK and cannot be null");
            }
            this.Kid = kid;
            // to ensure "n" is required (not null)
            if (n == null)
            {
                throw new ArgumentNullException("n is a required property for JWK and cannot be null");
            }
            this.N = n;
            // to ensure "e" is required (not null)
            if (e == null)
            {
                throw new ArgumentNullException("e is a required property for JWK and cannot be null");
            }
            this.E = e;
        }

        /// <summary>
        /// Gets or Sets Kty
        /// </summary>
        /*
        <example>RSA</example>
        */
        [DataMember(Name = "kty", IsRequired = true, EmitDefaultValue = true)]
        public string Kty { get; set; }

        /// <summary>
        /// Gets or Sets Use
        /// </summary>
        /*
        <example>sig</example>
        */
        [DataMember(Name = "use", IsRequired = true, EmitDefaultValue = true)]
        public string Use { get; set; }

        /// <summary>
        /// Gets or Sets Alg
        /// </summary>
        /*
        <example>RS256</example>
        */
        [DataMember(Name = "alg", IsRequired = true, EmitDefaultValue = true)]
        public string Alg { get; set; }

        /// <summary>
        /// Gets or Sets Kid
        /// </summary>
        [DataMember(Name = "kid", IsRequired = true, EmitDefaultValue = true)]
        public string Kid { get; set; }

        /// <summary>
        /// Base64url-encoded RSA modulus.
        /// </summary>
        /// <value>Base64url-encoded RSA modulus.</value>
        [DataMember(Name = "n", IsRequired = true, EmitDefaultValue = true)]
        public string N { get; set; }

        /// <summary>
        /// Base64url-encoded RSA exponent. Almost always \&quot;AQAB\&quot;.
        /// </summary>
        /// <value>Base64url-encoded RSA exponent. Almost always \&quot;AQAB\&quot;.</value>
        [DataMember(Name = "e", IsRequired = true, EmitDefaultValue = true)]
        public string E { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class JWK {\n");
            sb.Append("  Kty: ").Append(Kty).Append("\n");
            sb.Append("  Use: ").Append(Use).Append("\n");
            sb.Append("  Alg: ").Append(Alg).Append("\n");
            sb.Append("  Kid: ").Append(Kid).Append("\n");
            sb.Append("  N: ").Append(N).Append("\n");
            sb.Append("  E: ").Append(E).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
