/*
 * SpatioAPI
 *
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio/sdk-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Spatio.Sdk.Client.FileParameter;
using OpenAPIDateConverter = Spatio.Sdk.Client.OpenAPIDateConverter;

namespace Spatio.Sdk.Model
{
    /// <summary>
    /// Slide
    /// </summary>
    [DataContract(Name = "Slide")]
    public partial class Slide : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Slide" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Slide() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Slide" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="provider">provider.</param>
        /// <param name="accountId">accountId.</param>
        /// <param name="presentationId">presentationId (required).</param>
        /// <param name="title">title (required).</param>
        /// <param name="notes">Speaker notes..</param>
        /// <param name="layout">Free-form layout id. Provider-specific (&#x60;title&#x60;, &#x60;two-column&#x60;, &#x60;image-left&#x60;, custom). Not enumerated to avoid forcing a breaking change every time a provider adds one. .</param>
        /// <param name="backgroundColor">backgroundColor.</param>
        /// <param name="backgroundImageUrl">backgroundImageUrl.</param>
        /// <param name="textColor">textColor.</param>
        /// <param name="transition">Free-form transition id..</param>
        /// <param name="position">Zero-based position within the presentation. (required).</param>
        /// <param name="createdAt">createdAt (required).</param>
        /// <param name="updatedAt">updatedAt (required).</param>
        public Slide(string id = default, string provider = default, string accountId = default, string presentationId = default, string title = default, string notes = default, string layout = default, string backgroundColor = default, string backgroundImageUrl = default, string textColor = default, string transition = default, int position = default, DateTime createdAt = default, DateTime updatedAt = default)
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for Slide and cannot be null");
            }
            this.Id = id;
            // to ensure "presentationId" is required (not null)
            if (presentationId == null)
            {
                throw new ArgumentNullException("presentationId is a required property for Slide and cannot be null");
            }
            this.PresentationId = presentationId;
            // to ensure "title" is required (not null)
            if (title == null)
            {
                throw new ArgumentNullException("title is a required property for Slide and cannot be null");
            }
            this.Title = title;
            this.Position = position;
            this.CreatedAt = createdAt;
            this.UpdatedAt = updatedAt;
            this.Provider = provider;
            this.AccountId = accountId;
            this.Notes = notes;
            this.Layout = layout;
            this.BackgroundColor = backgroundColor;
            this.BackgroundImageUrl = backgroundImageUrl;
            this.TextColor = textColor;
            this.Transition = transition;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Provider
        /// </summary>
        [DataMember(Name = "provider", EmitDefaultValue = false)]
        public string Provider { get; set; }

        /// <summary>
        /// Gets or Sets AccountId
        /// </summary>
        [DataMember(Name = "accountId", EmitDefaultValue = false)]
        public string AccountId { get; set; }

        /// <summary>
        /// Gets or Sets PresentationId
        /// </summary>
        [DataMember(Name = "presentationId", IsRequired = true, EmitDefaultValue = true)]
        public string PresentationId { get; set; }

        /// <summary>
        /// Gets or Sets Title
        /// </summary>
        [DataMember(Name = "title", IsRequired = true, EmitDefaultValue = true)]
        public string Title { get; set; }

        /// <summary>
        /// Speaker notes.
        /// </summary>
        /// <value>Speaker notes.</value>
        [DataMember(Name = "notes", EmitDefaultValue = false)]
        public string Notes { get; set; }

        /// <summary>
        /// Free-form layout id. Provider-specific (&#x60;title&#x60;, &#x60;two-column&#x60;, &#x60;image-left&#x60;, custom). Not enumerated to avoid forcing a breaking change every time a provider adds one. 
        /// </summary>
        /// <value>Free-form layout id. Provider-specific (&#x60;title&#x60;, &#x60;two-column&#x60;, &#x60;image-left&#x60;, custom). Not enumerated to avoid forcing a breaking change every time a provider adds one. </value>
        [DataMember(Name = "layout", EmitDefaultValue = false)]
        public string Layout { get; set; }

        /// <summary>
        /// Gets or Sets BackgroundColor
        /// </summary>
        [DataMember(Name = "backgroundColor", EmitDefaultValue = false)]
        public string BackgroundColor { get; set; }

        /// <summary>
        /// Gets or Sets BackgroundImageUrl
        /// </summary>
        [DataMember(Name = "backgroundImageUrl", EmitDefaultValue = false)]
        public string BackgroundImageUrl { get; set; }

        /// <summary>
        /// Gets or Sets TextColor
        /// </summary>
        [DataMember(Name = "textColor", EmitDefaultValue = false)]
        public string TextColor { get; set; }

        /// <summary>
        /// Free-form transition id.
        /// </summary>
        /// <value>Free-form transition id.</value>
        [DataMember(Name = "transition", EmitDefaultValue = false)]
        public string Transition { get; set; }

        /// <summary>
        /// Zero-based position within the presentation.
        /// </summary>
        /// <value>Zero-based position within the presentation.</value>
        [DataMember(Name = "position", IsRequired = true, EmitDefaultValue = true)]
        public int Position { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [DataMember(Name = "createdAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        [DataMember(Name = "updatedAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTime UpdatedAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Slide {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Provider: ").Append(Provider).Append("\n");
            sb.Append("  AccountId: ").Append(AccountId).Append("\n");
            sb.Append("  PresentationId: ").Append(PresentationId).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Notes: ").Append(Notes).Append("\n");
            sb.Append("  Layout: ").Append(Layout).Append("\n");
            sb.Append("  BackgroundColor: ").Append(BackgroundColor).Append("\n");
            sb.Append("  BackgroundImageUrl: ").Append(BackgroundImageUrl).Append("\n");
            sb.Append("  TextColor: ").Append(TextColor).Append("\n");
            sb.Append("  Transition: ").Append(Transition).Append("\n");
            sb.Append("  Position: ").Append(Position).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
