/*
 * SpatioAPI
 *
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio-labs/spatio-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Spatio.Sdk.Client.FileParameter;
using OpenAPIDateConverter = Spatio.Sdk.Client.OpenAPIDateConverter;

namespace Spatio.Sdk.Model
{
    /// <summary>
    /// Inline formatting flags for a &#x60;RichTextObject&#x60;.
    /// </summary>
    [DataContract(Name = "TextAnnotations")]
    public partial class TextAnnotations : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TextAnnotations" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TextAnnotations() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TextAnnotations" /> class.
        /// </summary>
        /// <param name="bold">bold (required).</param>
        /// <param name="italic">italic (required).</param>
        /// <param name="strikethrough">strikethrough (required).</param>
        /// <param name="underline">underline (required).</param>
        /// <param name="code">code (required).</param>
        /// <param name="color">color.</param>
        public TextAnnotations(bool bold = default, bool italic = default, bool strikethrough = default, bool underline = default, bool code = default, string color = default)
        {
            this.Bold = bold;
            this.Italic = italic;
            this.Strikethrough = strikethrough;
            this.Underline = underline;
            this.Code = code;
            this.Color = color;
        }

        /// <summary>
        /// Gets or Sets Bold
        /// </summary>
        [DataMember(Name = "bold", IsRequired = true, EmitDefaultValue = true)]
        public bool Bold { get; set; }

        /// <summary>
        /// Gets or Sets Italic
        /// </summary>
        [DataMember(Name = "italic", IsRequired = true, EmitDefaultValue = true)]
        public bool Italic { get; set; }

        /// <summary>
        /// Gets or Sets Strikethrough
        /// </summary>
        [DataMember(Name = "strikethrough", IsRequired = true, EmitDefaultValue = true)]
        public bool Strikethrough { get; set; }

        /// <summary>
        /// Gets or Sets Underline
        /// </summary>
        [DataMember(Name = "underline", IsRequired = true, EmitDefaultValue = true)]
        public bool Underline { get; set; }

        /// <summary>
        /// Gets or Sets Code
        /// </summary>
        [DataMember(Name = "code", IsRequired = true, EmitDefaultValue = true)]
        public bool Code { get; set; }

        /// <summary>
        /// Gets or Sets Color
        /// </summary>
        [DataMember(Name = "color", EmitDefaultValue = false)]
        public string Color { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TextAnnotations {\n");
            sb.Append("  Bold: ").Append(Bold).Append("\n");
            sb.Append("  Italic: ").Append(Italic).Append("\n");
            sb.Append("  Strikethrough: ").Append(Strikethrough).Append("\n");
            sb.Append("  Underline: ").Append(Underline).Append("\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  Color: ").Append(Color).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
