/*
 * SpatioAPI
 *
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio-labs/spatio-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Spatio.Sdk.Client.FileParameter;
using OpenAPIDateConverter = Spatio.Sdk.Client.OpenAPIDateConverter;

namespace Spatio.Sdk.Model
{
    /// <summary>
    /// Sparse update. &#x60;updates&#x60; is a free-form map of fields to change; only keys present are applied. The server-side capability gate rejects fields that the underlying provider doesn&#39;t support. 
    /// </summary>
    [DataContract(Name = "UpdateEventRequest")]
    public partial class UpdateEventRequest : IValidatableObject
    {
        /// <summary>
        /// Defines SendUpdates
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum SendUpdatesEnum
        {
            /// <summary>
            /// Enum All for value: all
            /// </summary>
            [EnumMember(Value = "all")]
            All = 1,

            /// <summary>
            /// Enum ExternalOnly for value: externalOnly
            /// </summary>
            [EnumMember(Value = "externalOnly")]
            ExternalOnly = 2,

            /// <summary>
            /// Enum None for value: none
            /// </summary>
            [EnumMember(Value = "none")]
            None = 3
        }


        /// <summary>
        /// Gets or Sets SendUpdates
        /// </summary>
        [DataMember(Name = "send_updates", EmitDefaultValue = false)]
        public SendUpdatesEnum? SendUpdates { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateEventRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UpdateEventRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateEventRequest" /> class.
        /// </summary>
        /// <param name="accountId">accountId (required).</param>
        /// <param name="updates">updates (required).</param>
        /// <param name="sendUpdates">sendUpdates.</param>
        public UpdateEventRequest(string accountId = default, Dictionary<string, Object> updates = default, SendUpdatesEnum? sendUpdates = default)
        {
            // to ensure "accountId" is required (not null)
            if (accountId == null)
            {
                throw new ArgumentNullException("accountId is a required property for UpdateEventRequest and cannot be null");
            }
            this.AccountId = accountId;
            // to ensure "updates" is required (not null)
            if (updates == null)
            {
                throw new ArgumentNullException("updates is a required property for UpdateEventRequest and cannot be null");
            }
            this.Updates = updates;
            this.SendUpdates = sendUpdates;
        }

        /// <summary>
        /// Gets or Sets AccountId
        /// </summary>
        [DataMember(Name = "account_id", IsRequired = true, EmitDefaultValue = true)]
        public string AccountId { get; set; }

        /// <summary>
        /// Gets or Sets Updates
        /// </summary>
        [DataMember(Name = "updates", IsRequired = true, EmitDefaultValue = true)]
        public Dictionary<string, Object> Updates { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateEventRequest {\n");
            sb.Append("  AccountId: ").Append(AccountId).Append("\n");
            sb.Append("  Updates: ").Append(Updates).Append("\n");
            sb.Append("  SendUpdates: ").Append(SendUpdates).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
