/*
 * SpatioAPI
 *
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio-labs/spatio-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Spatio.Sdk.Model;
using Spatio.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Spatio.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing BlockContent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BlockContentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BlockContent
        //private BlockContent instance;

        public BlockContentTests()
        {
            // TODO uncomment below to create an instance of BlockContent
            //instance = new BlockContent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BlockContent
        /// </summary>
        [Fact]
        public void BlockContentInstanceTest()
        {
            // TODO uncomment below to test "IsType" BlockContent
            //Assert.IsType<BlockContent>(instance);
        }

        /// <summary>
        /// Test the property 'RichText'
        /// </summary>
        [Fact]
        public void RichTextTest()
        {
            // TODO unit test for the property 'RichText'
        }

        /// <summary>
        /// Test the property 'Language'
        /// </summary>
        [Fact]
        public void LanguageTest()
        {
            // TODO unit test for the property 'Language'
        }

        /// <summary>
        /// Test the property 'Checked'
        /// </summary>
        [Fact]
        public void CheckedTest()
        {
            // TODO unit test for the property 'Checked'
        }

        /// <summary>
        /// Test the property 'Icon'
        /// </summary>
        [Fact]
        public void IconTest()
        {
            // TODO unit test for the property 'Icon'
        }

        /// <summary>
        /// Test the property 'Color'
        /// </summary>
        [Fact]
        public void ColorTest()
        {
            // TODO unit test for the property 'Color'
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

        /// <summary>
        /// Test the property 'Caption'
        /// </summary>
        [Fact]
        public void CaptionTest()
        {
            // TODO unit test for the property 'Caption'
        }

        /// <summary>
        /// Test the property 'AltText'
        /// </summary>
        [Fact]
        public void AltTextTest()
        {
            // TODO unit test for the property 'AltText'
        }

        /// <summary>
        /// Test the property 'EmbedUrl'
        /// </summary>
        [Fact]
        public void EmbedUrlTest()
        {
            // TODO unit test for the property 'EmbedUrl'
        }

        /// <summary>
        /// Test the property 'Cells'
        /// </summary>
        [Fact]
        public void CellsTest()
        {
            // TODO unit test for the property 'Cells'
        }

        /// <summary>
        /// Test the property 'Expression'
        /// </summary>
        [Fact]
        public void ExpressionTest()
        {
            // TODO unit test for the property 'Expression'
        }
    }
}
