/*
 * SpatioAPI
 *
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio-labs/spatio-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Spatio.Sdk.Model;
using Spatio.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Spatio.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing ClientRegistrationRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ClientRegistrationRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ClientRegistrationRequest
        //private ClientRegistrationRequest instance;

        public ClientRegistrationRequestTests()
        {
            // TODO uncomment below to create an instance of ClientRegistrationRequest
            //instance = new ClientRegistrationRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ClientRegistrationRequest
        /// </summary>
        [Fact]
        public void ClientRegistrationRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ClientRegistrationRequest
            //Assert.IsType<ClientRegistrationRequest>(instance);
        }

        /// <summary>
        /// Test the property 'ClientName'
        /// </summary>
        [Fact]
        public void ClientNameTest()
        {
            // TODO unit test for the property 'ClientName'
        }

        /// <summary>
        /// Test the property 'RedirectUris'
        /// </summary>
        [Fact]
        public void RedirectUrisTest()
        {
            // TODO unit test for the property 'RedirectUris'
        }

        /// <summary>
        /// Test the property 'GrantTypes'
        /// </summary>
        [Fact]
        public void GrantTypesTest()
        {
            // TODO unit test for the property 'GrantTypes'
        }

        /// <summary>
        /// Test the property 'ResponseTypes'
        /// </summary>
        [Fact]
        public void ResponseTypesTest()
        {
            // TODO unit test for the property 'ResponseTypes'
        }

        /// <summary>
        /// Test the property 'Scope'
        /// </summary>
        [Fact]
        public void ScopeTest()
        {
            // TODO unit test for the property 'Scope'
        }

        /// <summary>
        /// Test the property 'TokenEndpointAuthMethod'
        /// </summary>
        [Fact]
        public void TokenEndpointAuthMethodTest()
        {
            // TODO unit test for the property 'TokenEndpointAuthMethod'
        }

        /// <summary>
        /// Test the property 'ClientUri'
        /// </summary>
        [Fact]
        public void ClientUriTest()
        {
            // TODO unit test for the property 'ClientUri'
        }

        /// <summary>
        /// Test the property 'LogoUri'
        /// </summary>
        [Fact]
        public void LogoUriTest()
        {
            // TODO unit test for the property 'LogoUri'
        }

        /// <summary>
        /// Test the property 'PolicyUri'
        /// </summary>
        [Fact]
        public void PolicyUriTest()
        {
            // TODO unit test for the property 'PolicyUri'
        }

        /// <summary>
        /// Test the property 'TosUri'
        /// </summary>
        [Fact]
        public void TosUriTest()
        {
            // TODO unit test for the property 'TosUri'
        }
    }
}
