/*
 * SpatioAPI
 *
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio/sdk-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using Spatio.Sdk.Client;
using Spatio.Sdk.Api;
// uncomment below to import models
//using Spatio.Sdk.Model;

namespace Spatio.Sdk.Test.Api
{
    /// <summary>
    ///  Class for testing CallsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class CallsApiTests : IDisposable
    {
        private CallsApi instance;

        public CallsApiTests()
        {
            instance = new CallsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CallsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' CallsApi
            //Assert.IsType<CallsApi>(instance);
        }

        /// <summary>
        /// Test CreateCall
        /// </summary>
        [Fact]
        public void CreateCallTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateCallRequest? createCallRequest = null;
            //var response = instance.CreateCall(createCallRequest);
            //Assert.IsType<SpatioCall>(response);
        }

        /// <summary>
        /// Test CreateMeetingRoom
        /// </summary>
        [Fact]
        public void CreateMeetingRoomTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateMeetingRoomRequest createMeetingRoomRequest = null;
            //var response = instance.CreateMeetingRoom(createMeetingRoomRequest);
            //Assert.IsType<MeetingRoom>(response);
        }

        /// <summary>
        /// Test DeleteCallRecording
        /// </summary>
        [Fact]
        public void DeleteCallRecordingTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string recordingId = null;
            //instance.DeleteCallRecording(recordingId);
        }

        /// <summary>
        /// Test EndCall
        /// </summary>
        [Fact]
        public void EndCallTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //instance.EndCall(id);
        }

        /// <summary>
        /// Test GetBandwidthHistory
        /// </summary>
        [Fact]
        public void GetBandwidthHistoryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetBandwidthHistory();
            //Assert.IsType<Dictionary<string, Object>>(response);
        }

        /// <summary>
        /// Test GetBandwidthSummary
        /// </summary>
        [Fact]
        public void GetBandwidthSummaryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetBandwidthSummary();
            //Assert.IsType<Dictionary<string, Object>>(response);
        }

        /// <summary>
        /// Test GetCall
        /// </summary>
        [Fact]
        public void GetCallTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.GetCall(id);
            //Assert.IsType<SpatioCall>(response);
        }

        /// <summary>
        /// Test GetMeetingRoom
        /// </summary>
        [Fact]
        public void GetMeetingRoomTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.GetMeetingRoom(id);
            //Assert.IsType<MeetingRoom>(response);
        }

        /// <summary>
        /// Test JoinCall
        /// </summary>
        [Fact]
        public void JoinCallTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.JoinCall(id);
            //Assert.IsType<Dictionary<string, Object>>(response);
        }

        /// <summary>
        /// Test LeaveCall
        /// </summary>
        [Fact]
        public void LeaveCallTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //instance.LeaveCall(id);
        }

        /// <summary>
        /// Test ListActiveCalls
        /// </summary>
        [Fact]
        public void ListActiveCallsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ListActiveCalls();
            //Assert.IsType<CallListResponse>(response);
        }

        /// <summary>
        /// Test ListCallRecordings
        /// </summary>
        [Fact]
        public void ListCallRecordingsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.ListCallRecordings(id);
            //Assert.IsType<CallRecordingListResponse>(response);
        }

        /// <summary>
        /// Test StartCallRecording
        /// </summary>
        [Fact]
        public void StartCallRecordingTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.StartCallRecording(id);
            //Assert.IsType<CallRecording>(response);
        }

        /// <summary>
        /// Test StopCallRecording
        /// </summary>
        [Fact]
        public void StopCallRecordingTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //string recordingId = null;
            //var response = instance.StopCallRecording(id, recordingId);
            //Assert.IsType<CallRecording>(response);
        }

        /// <summary>
        /// Test UpdateCallParticipantState
        /// </summary>
        [Fact]
        public void UpdateCallParticipantStateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //UpdateParticipantStateRequest updateParticipantStateRequest = null;
            //var response = instance.UpdateCallParticipantState(id, updateParticipantStateRequest);
            //Assert.IsType<Dictionary<string, Object>>(response);
        }

        /// <summary>
        /// Test WorkspaceCreateCall
        /// </summary>
        [Fact]
        public void WorkspaceCreateCallTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string org = null;
            //string workspace = null;
            //Dictionary<string, Object> requestBody = null;
            //var response = instance.WorkspaceCreateCall(org, workspace, requestBody);
            //Assert.IsType<Dictionary<string, Object>>(response);
        }

        /// <summary>
        /// Test WorkspaceCreateMeetingRoom
        /// </summary>
        [Fact]
        public void WorkspaceCreateMeetingRoomTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string org = null;
            //string workspace = null;
            //Dictionary<string, Object> requestBody = null;
            //var response = instance.WorkspaceCreateMeetingRoom(org, workspace, requestBody);
            //Assert.IsType<Dictionary<string, Object>>(response);
        }

        /// <summary>
        /// Test WorkspaceDeleteCallRecording
        /// </summary>
        [Fact]
        public void WorkspaceDeleteCallRecordingTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string org = null;
            //string workspace = null;
            //string recordingId = null;
            //instance.WorkspaceDeleteCallRecording(org, workspace, recordingId);
        }

        /// <summary>
        /// Test WorkspaceEndCall
        /// </summary>
        [Fact]
        public void WorkspaceEndCallTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string org = null;
            //string workspace = null;
            //string id = null;
            //instance.WorkspaceEndCall(org, workspace, id);
        }

        /// <summary>
        /// Test WorkspaceGetBandwidthHistory
        /// </summary>
        [Fact]
        public void WorkspaceGetBandwidthHistoryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string org = null;
            //string workspace = null;
            //var response = instance.WorkspaceGetBandwidthHistory(org, workspace);
            //Assert.IsType<Dictionary<string, Object>>(response);
        }

        /// <summary>
        /// Test WorkspaceGetBandwidthSummary
        /// </summary>
        [Fact]
        public void WorkspaceGetBandwidthSummaryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string org = null;
            //string workspace = null;
            //var response = instance.WorkspaceGetBandwidthSummary(org, workspace);
            //Assert.IsType<Dictionary<string, Object>>(response);
        }

        /// <summary>
        /// Test WorkspaceGetCall
        /// </summary>
        [Fact]
        public void WorkspaceGetCallTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string org = null;
            //string workspace = null;
            //string id = null;
            //var response = instance.WorkspaceGetCall(org, workspace, id);
            //Assert.IsType<Dictionary<string, Object>>(response);
        }

        /// <summary>
        /// Test WorkspaceGetMeetingRoom
        /// </summary>
        [Fact]
        public void WorkspaceGetMeetingRoomTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string org = null;
            //string workspace = null;
            //string id = null;
            //var response = instance.WorkspaceGetMeetingRoom(org, workspace, id);
            //Assert.IsType<Dictionary<string, Object>>(response);
        }

        /// <summary>
        /// Test WorkspaceJoinCall
        /// </summary>
        [Fact]
        public void WorkspaceJoinCallTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string org = null;
            //string workspace = null;
            //string id = null;
            //var response = instance.WorkspaceJoinCall(org, workspace, id);
            //Assert.IsType<Dictionary<string, Object>>(response);
        }

        /// <summary>
        /// Test WorkspaceLeaveCall
        /// </summary>
        [Fact]
        public void WorkspaceLeaveCallTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string org = null;
            //string workspace = null;
            //string id = null;
            //instance.WorkspaceLeaveCall(org, workspace, id);
        }

        /// <summary>
        /// Test WorkspaceListActiveCalls
        /// </summary>
        [Fact]
        public void WorkspaceListActiveCallsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string org = null;
            //string workspace = null;
            //var response = instance.WorkspaceListActiveCalls(org, workspace);
            //Assert.IsType<Dictionary<string, Object>>(response);
        }

        /// <summary>
        /// Test WorkspaceListCallRecordings
        /// </summary>
        [Fact]
        public void WorkspaceListCallRecordingsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string org = null;
            //string workspace = null;
            //string id = null;
            //var response = instance.WorkspaceListCallRecordings(org, workspace, id);
            //Assert.IsType<Dictionary<string, Object>>(response);
        }

        /// <summary>
        /// Test WorkspaceStartCallRecording
        /// </summary>
        [Fact]
        public void WorkspaceStartCallRecordingTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string org = null;
            //string workspace = null;
            //string id = null;
            //var response = instance.WorkspaceStartCallRecording(org, workspace, id);
            //Assert.IsType<Dictionary<string, Object>>(response);
        }

        /// <summary>
        /// Test WorkspaceStopCallRecording
        /// </summary>
        [Fact]
        public void WorkspaceStopCallRecordingTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string org = null;
            //string workspace = null;
            //string id = null;
            //string recordingId = null;
            //var response = instance.WorkspaceStopCallRecording(org, workspace, id, recordingId);
            //Assert.IsType<Dictionary<string, Object>>(response);
        }

        /// <summary>
        /// Test WorkspaceUpdateCallParticipant
        /// </summary>
        [Fact]
        public void WorkspaceUpdateCallParticipantTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string org = null;
            //string workspace = null;
            //string id = null;
            //Dictionary<string, Object> requestBody = null;
            //var response = instance.WorkspaceUpdateCallParticipant(org, workspace, id, requestBody);
            //Assert.IsType<Dictionary<string, Object>>(response);
        }
    }
}
