/*
 * SpatioAPI
 *
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio-labs/spatio-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using Spatio.Sdk.Client;
using Spatio.Sdk.Api;
// uncomment below to import models
//using Spatio.Sdk.Model;

namespace Spatio.Sdk.Test.Api
{
    /// <summary>
    ///  Class for testing ContactsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ContactsApiTests : IDisposable
    {
        private ContactsApi instance;

        public ContactsApiTests()
        {
            instance = new ContactsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ContactsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ContactsApi
            //Assert.IsType<ContactsApi>(instance);
        }

        /// <summary>
        /// Test AssignContactCategory
        /// </summary>
        [Fact]
        public void AssignContactCategoryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //AssignContactCategoryRequest assignContactCategoryRequest = null;
            //instance.AssignContactCategory(id, assignContactCategoryRequest);
        }

        /// <summary>
        /// Test CreateContact
        /// </summary>
        [Fact]
        public void CreateContactTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateContactRequest createContactRequest = null;
            //var response = instance.CreateContact(createContactRequest);
            //Assert.IsType<Contact>(response);
        }

        /// <summary>
        /// Test CreateContactCategory
        /// </summary>
        [Fact]
        public void CreateContactCategoryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateContactCategoryRequest createContactCategoryRequest = null;
            //var response = instance.CreateContactCategory(createContactCategoryRequest);
            //Assert.IsType<ContactCategory>(response);
        }

        /// <summary>
        /// Test DeleteContact
        /// </summary>
        [Fact]
        public void DeleteContactTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //instance.DeleteContact(id);
        }

        /// <summary>
        /// Test DeleteContactCategory
        /// </summary>
        [Fact]
        public void DeleteContactCategoryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //instance.DeleteContactCategory(id);
        }

        /// <summary>
        /// Test GetContact
        /// </summary>
        [Fact]
        public void GetContactTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.GetContact(id);
            //Assert.IsType<Contact>(response);
        }

        /// <summary>
        /// Test ListContactCategories
        /// </summary>
        [Fact]
        public void ListContactCategoriesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string organizationId = null;
            //var response = instance.ListContactCategories(organizationId);
            //Assert.IsType<ContactCategoryListResponse>(response);
        }

        /// <summary>
        /// Test ListContactProviders
        /// </summary>
        [Fact]
        public void ListContactProvidersTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ListContactProviders();
            //Assert.IsType<ContactProviderListResponse>(response);
        }

        /// <summary>
        /// Test ListContacts
        /// </summary>
        [Fact]
        public void ListContactsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? limit = null;
            //string? provider = null;
            //string? search = null;
            //var response = instance.ListContacts(limit, provider, search);
            //Assert.IsType<ContactListResponse>(response);
        }

        /// <summary>
        /// Test UnassignContactCategory
        /// </summary>
        [Fact]
        public void UnassignContactCategoryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //string categoryId = null;
            //instance.UnassignContactCategory(id, categoryId);
        }

        /// <summary>
        /// Test UpdateContact
        /// </summary>
        [Fact]
        public void UpdateContactTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //UpdateContactRequest updateContactRequest = null;
            //var response = instance.UpdateContact(id, updateContactRequest);
            //Assert.IsType<Contact>(response);
        }

        /// <summary>
        /// Test UpdateContactCategory
        /// </summary>
        [Fact]
        public void UpdateContactCategoryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //UpdateContactCategoryRequest updateContactCategoryRequest = null;
            //var response = instance.UpdateContactCategory(id, updateContactCategoryRequest);
            //Assert.IsType<ContactCategory>(response);
        }
    }
}
