/*
 * SpatioAPI
 *
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio/sdk-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using Spatio.Sdk.Client;
using Spatio.Sdk.Api;
// uncomment below to import models
//using Spatio.Sdk.Model;

namespace Spatio.Sdk.Test.Api
{
    /// <summary>
    ///  Class for testing FoldersApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class FoldersApiTests : IDisposable
    {
        private FoldersApi instance;

        public FoldersApiTests()
        {
            instance = new FoldersApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FoldersApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' FoldersApi
            //Assert.IsType<FoldersApi>(instance);
        }

        /// <summary>
        /// Test CreateEmailFolder
        /// </summary>
        [Fact]
        public void CreateEmailFolderTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateEmailFolderRequest createEmailFolderRequest = null;
            //var response = instance.CreateEmailFolder(createEmailFolderRequest);
            //Assert.IsType<EmailFolder>(response);
        }

        /// <summary>
        /// Test DeleteEmailFolder
        /// </summary>
        [Fact]
        public void DeleteEmailFolderTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //instance.DeleteEmailFolder(id);
        }

        /// <summary>
        /// Test ListEmailFolders
        /// </summary>
        [Fact]
        public void ListEmailFoldersTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ListEmailFolders();
            //Assert.IsType<EmailFolderListResponse>(response);
        }

        /// <summary>
        /// Test ListFolderEmails
        /// </summary>
        [Fact]
        public void ListFolderEmailsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.ListFolderEmails(id);
            //Assert.IsType<Dictionary<string, Object>>(response);
        }

        /// <summary>
        /// Test MoveEmailsToFolder
        /// </summary>
        [Fact]
        public void MoveEmailsToFolderTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //MoveEmailsRequest moveEmailsRequest = null;
            //var response = instance.MoveEmailsToFolder(id, moveEmailsRequest);
            //Assert.IsType<Dictionary<string, Object>>(response);
        }

        /// <summary>
        /// Test UpdateEmailFolder
        /// </summary>
        [Fact]
        public void UpdateEmailFolderTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //UpdateEmailFolderRequest updateEmailFolderRequest = null;
            //var response = instance.UpdateEmailFolder(id, updateEmailFolderRequest);
            //Assert.IsType<EmailFolder>(response);
        }
    }
}
