/*
 * SpatioAPI
 *
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio/sdk-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using Spatio.Sdk.Client;
using Spatio.Sdk.Api;
// uncomment below to import models
//using Spatio.Sdk.Model;

namespace Spatio.Sdk.Test.Api
{
    /// <summary>
    ///  Class for testing KeybindingsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class KeybindingsApiTests : IDisposable
    {
        private KeybindingsApi instance;

        public KeybindingsApiTests()
        {
            instance = new KeybindingsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of KeybindingsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' KeybindingsApi
            //Assert.IsType<KeybindingsApi>(instance);
        }

        /// <summary>
        /// Test DeleteKeyBinding
        /// </summary>
        [Fact]
        public void DeleteKeyBindingTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //instance.DeleteKeyBinding(id);
        }

        /// <summary>
        /// Test GetDefaultKeyBindings
        /// </summary>
        [Fact]
        public void GetDefaultKeyBindingsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetDefaultKeyBindings();
            //Assert.IsType<KeyBindingListResponse>(response);
        }

        /// <summary>
        /// Test ListKeyBindings
        /// </summary>
        [Fact]
        public void ListKeyBindingsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ListKeyBindings();
            //Assert.IsType<KeyBindingListResponse>(response);
        }

        /// <summary>
        /// Test ResetAllKeyBindings
        /// </summary>
        [Fact]
        public void ResetAllKeyBindingsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.ResetAllKeyBindings();
        }

        /// <summary>
        /// Test UpdateKeyBinding
        /// </summary>
        [Fact]
        public void UpdateKeyBindingTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //UpdateKeyBindingRequest updateKeyBindingRequest = null;
            //var response = instance.UpdateKeyBinding(id, updateKeyBindingRequest);
            //Assert.IsType<KeyBinding>(response);
        }

        /// <summary>
        /// Test ValidateKeyBinding
        /// </summary>
        [Fact]
        public void ValidateKeyBindingTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ValidateKeyBindingRequest validateKeyBindingRequest = null;
            //var response = instance.ValidateKeyBinding(validateKeyBindingRequest);
            //Assert.IsType<ValidateKeyBindingResponse>(response);
        }
    }
}
