/*
 * SpatioAPI
 *
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio/sdk-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using Spatio.Sdk.Client;
using Spatio.Sdk.Api;
// uncomment below to import models
//using Spatio.Sdk.Model;

namespace Spatio.Sdk.Test.Api
{
    /// <summary>
    ///  Class for testing OrganizationsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class OrganizationsApiTests : IDisposable
    {
        private OrganizationsApi instance;

        public OrganizationsApiTests()
        {
            instance = new OrganizationsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrganizationsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' OrganizationsApi
            //Assert.IsType<OrganizationsApi>(instance);
        }

        /// <summary>
        /// Test AcceptOrganizationInvitation
        /// </summary>
        [Fact]
        public void AcceptOrganizationInvitationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string org = null;
            //AcceptOrganizationInvitationRequest acceptOrganizationInvitationRequest = null;
            //var response = instance.AcceptOrganizationInvitation(org, acceptOrganizationInvitationRequest);
            //Assert.IsType<Dictionary<string, Object>>(response);
        }

        /// <summary>
        /// Test AddOrganizationMember
        /// </summary>
        [Fact]
        public void AddOrganizationMemberTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string org = null;
            //AddOrganizationMemberRequest addOrganizationMemberRequest = null;
            //var response = instance.AddOrganizationMember(org, addOrganizationMemberRequest);
            //Assert.IsType<Dictionary<string, Object>>(response);
        }

        /// <summary>
        /// Test CreateOrganization
        /// </summary>
        [Fact]
        public void CreateOrganizationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateOrganizationRequest createOrganizationRequest = null;
            //var response = instance.CreateOrganization(createOrganizationRequest);
            //Assert.IsType<Dictionary<string, Object>>(response);
        }

        /// <summary>
        /// Test CreateOrganizationConcept
        /// </summary>
        [Fact]
        public void CreateOrganizationConceptTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string org = null;
            //Dictionary<string, Object> requestBody = null;
            //var response = instance.CreateOrganizationConcept(org, requestBody);
            //Assert.IsType<Dictionary<string, Object>>(response);
        }

        /// <summary>
        /// Test CreateOrganizationCustomRole
        /// </summary>
        [Fact]
        public void CreateOrganizationCustomRoleTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string org = null;
            //Dictionary<string, Object> requestBody = null;
            //var response = instance.CreateOrganizationCustomRole(org, requestBody);
            //Assert.IsType<Dictionary<string, Object>>(response);
        }

        /// <summary>
        /// Test CreateOrganizationInvitation
        /// </summary>
        [Fact]
        public void CreateOrganizationInvitationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string org = null;
            //CreateOrganizationInvitationRequest createOrganizationInvitationRequest = null;
            //var response = instance.CreateOrganizationInvitation(org, createOrganizationInvitationRequest);
            //Assert.IsType<OrganizationInvitation>(response);
        }

        /// <summary>
        /// Test CreateOrganizationWorkspace
        /// </summary>
        [Fact]
        public void CreateOrganizationWorkspaceTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string org = null;
            //CreateWorkspaceRequest createWorkspaceRequest = null;
            //var response = instance.CreateOrganizationWorkspace(org, createWorkspaceRequest);
            //Assert.IsType<WorkspaceEnvelope>(response);
        }

        /// <summary>
        /// Test DeleteOrganization
        /// </summary>
        [Fact]
        public void DeleteOrganizationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string org = null;
            //instance.DeleteOrganization(org);
        }

        /// <summary>
        /// Test DeleteOrganizationConcept
        /// </summary>
        [Fact]
        public void DeleteOrganizationConceptTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string org = null;
            //string slug = null;
            //instance.DeleteOrganizationConcept(org, slug);
        }

        /// <summary>
        /// Test DeleteOrganizationCustomRole
        /// </summary>
        [Fact]
        public void DeleteOrganizationCustomRoleTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string org = null;
            //string roleId = null;
            //instance.DeleteOrganizationCustomRole(org, roleId);
        }

        /// <summary>
        /// Test DeleteOrganizationLogo
        /// </summary>
        [Fact]
        public void DeleteOrganizationLogoTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string org = null;
            //instance.DeleteOrganizationLogo(org);
        }

        /// <summary>
        /// Test GetOrganization
        /// </summary>
        [Fact]
        public void GetOrganizationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string org = null;
            //var response = instance.GetOrganization(org);
            //Assert.IsType<OrganizationDetailLegacy>(response);
        }

        /// <summary>
        /// Test GetOrganizationConcept
        /// </summary>
        [Fact]
        public void GetOrganizationConceptTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string org = null;
            //string slug = null;
            //var response = instance.GetOrganizationConcept(org, slug);
            //Assert.IsType<Dictionary<string, Object>>(response);
        }

        /// <summary>
        /// Test ListMyOrganizations
        /// </summary>
        [Fact]
        public void ListMyOrganizationsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ListMyOrganizations();
            //Assert.IsType<OrganizationListResponse>(response);
        }

        /// <summary>
        /// Test ListOrganizationAuditLog
        /// </summary>
        [Fact]
        public void ListOrganizationAuditLogTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string org = null;
            //int? limit = null;
            //string? cursor = null;
            //var response = instance.ListOrganizationAuditLog(org, limit, cursor);
            //Assert.IsType<Dictionary<string, Object>>(response);
        }

        /// <summary>
        /// Test ListOrganizationConcepts
        /// </summary>
        [Fact]
        public void ListOrganizationConceptsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string org = null;
            //var response = instance.ListOrganizationConcepts(org);
            //Assert.IsType<Dictionary<string, Object>>(response);
        }

        /// <summary>
        /// Test ListOrganizationCustomRoles
        /// </summary>
        [Fact]
        public void ListOrganizationCustomRolesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string org = null;
            //var response = instance.ListOrganizationCustomRoles(org);
            //Assert.IsType<Dictionary<string, Object>>(response);
        }

        /// <summary>
        /// Test ListOrganizationInvitations
        /// </summary>
        [Fact]
        public void ListOrganizationInvitationsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string org = null;
            //var response = instance.ListOrganizationInvitations(org);
            //Assert.IsType<OrganizationInvitationListResponse>(response);
        }

        /// <summary>
        /// Test ListOrganizationMembers
        /// </summary>
        [Fact]
        public void ListOrganizationMembersTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string org = null;
            //var response = instance.ListOrganizationMembers(org);
            //Assert.IsType<OrganizationMemberListResponse>(response);
        }

        /// <summary>
        /// Test ListOrganizationWorkspaces
        /// </summary>
        [Fact]
        public void ListOrganizationWorkspacesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string org = null;
            //var response = instance.ListOrganizationWorkspaces(org);
            //Assert.IsType<WorkspaceListResponse>(response);
        }

        /// <summary>
        /// Test RemoveOrganizationMember
        /// </summary>
        [Fact]
        public void RemoveOrganizationMemberTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string org = null;
            //string memberId = null;
            //instance.RemoveOrganizationMember(org, memberId);
        }

        /// <summary>
        /// Test ResendOrganizationInvitation
        /// </summary>
        [Fact]
        public void ResendOrganizationInvitationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string org = null;
            //string invitationId = null;
            //var response = instance.ResendOrganizationInvitation(org, invitationId);
            //Assert.IsType<OrganizationInvitation>(response);
        }

        /// <summary>
        /// Test RevokeOrganizationInvitation
        /// </summary>
        [Fact]
        public void RevokeOrganizationInvitationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string org = null;
            //string invitationId = null;
            //instance.RevokeOrganizationInvitation(org, invitationId);
        }

        /// <summary>
        /// Test UpdateOrganization
        /// </summary>
        [Fact]
        public void UpdateOrganizationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string org = null;
            //UpdateOrganizationRequest updateOrganizationRequest = null;
            //var response = instance.UpdateOrganization(org, updateOrganizationRequest);
            //Assert.IsType<Dictionary<string, Object>>(response);
        }

        /// <summary>
        /// Test UpdateOrganizationConcept
        /// </summary>
        [Fact]
        public void UpdateOrganizationConceptTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string org = null;
            //string slug = null;
            //Dictionary<string, Object> requestBody = null;
            //var response = instance.UpdateOrganizationConcept(org, slug, requestBody);
            //Assert.IsType<Dictionary<string, Object>>(response);
        }

        /// <summary>
        /// Test UpdateOrganizationCustomRole
        /// </summary>
        [Fact]
        public void UpdateOrganizationCustomRoleTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string org = null;
            //string roleId = null;
            //Dictionary<string, Object> requestBody = null;
            //var response = instance.UpdateOrganizationCustomRole(org, roleId, requestBody);
            //Assert.IsType<Dictionary<string, Object>>(response);
        }

        /// <summary>
        /// Test UpdateOrganizationMember
        /// </summary>
        [Fact]
        public void UpdateOrganizationMemberTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string org = null;
            //string memberId = null;
            //UpdateOrganizationMemberRequest updateOrganizationMemberRequest = null;
            //var response = instance.UpdateOrganizationMember(org, memberId, updateOrganizationMemberRequest);
            //Assert.IsType<Dictionary<string, Object>>(response);
        }

        /// <summary>
        /// Test UploadOrganizationLogo
        /// </summary>
        [Fact]
        public void UploadOrganizationLogoTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string org = null;
            //FileParameter? file = null;
            //var response = instance.UploadOrganizationLogo(org, file);
            //Assert.IsType<Dictionary<string, Object>>(response);
        }
    }
}
