/*
 * SpatioAPI
 *
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio/sdk-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using Spatio.Sdk.Client;
using Spatio.Sdk.Api;
// uncomment below to import models
//using Spatio.Sdk.Model;

namespace Spatio.Sdk.Test.Api
{
    /// <summary>
    ///  Class for testing RealtimeApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class RealtimeApiTests : IDisposable
    {
        private RealtimeApi instance;

        public RealtimeApiTests()
        {
            instance = new RealtimeApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RealtimeApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' RealtimeApi
            //Assert.IsType<RealtimeApi>(instance);
        }

        /// <summary>
        /// Test IssueCollaborationToken
        /// </summary>
        [Fact]
        public void IssueCollaborationTokenTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //IssueCollaborationTokenRequest? issueCollaborationTokenRequest = null;
            //var response = instance.IssueCollaborationToken(issueCollaborationTokenRequest);
            //Assert.IsType<IssueCollaborationToken200Response>(response);
        }
    }
}
