/*
 * SpatioAPI
 *
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio/sdk-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using Spatio.Sdk.Client;
using Spatio.Sdk.Api;
// uncomment below to import models
//using Spatio.Sdk.Model;

namespace Spatio.Sdk.Test.Api
{
    /// <summary>
    ///  Class for testing SheetsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class SheetsApiTests : IDisposable
    {
        private SheetsApi instance;

        public SheetsApiTests()
        {
            instance = new SheetsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SheetsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' SheetsApi
            //Assert.IsType<SheetsApi>(instance);
        }

        /// <summary>
        /// Test CreateSheet
        /// </summary>
        [Fact]
        public void CreateSheetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateSheetRequest createSheetRequest = null;
            //string? accountId = null;
            //string? provider = null;
            //string? xWorkspaceID = null;
            //var response = instance.CreateSheet(createSheetRequest, accountId, provider, xWorkspaceID);
            //Assert.IsType<Sheet>(response);
        }

        /// <summary>
        /// Test CreateSheetRow
        /// </summary>
        [Fact]
        public void CreateSheetRowTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //CreateRowRequest createRowRequest = null;
            //string? accountId = null;
            //string? xWorkspaceID = null;
            //var response = instance.CreateSheetRow(id, createRowRequest, accountId, xWorkspaceID);
            //Assert.IsType<Row>(response);
        }

        /// <summary>
        /// Test DeleteSheet
        /// </summary>
        [Fact]
        public void DeleteSheetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //string? accountId = null;
            //string? xWorkspaceID = null;
            //var response = instance.DeleteSheet(id, accountId, xWorkspaceID);
            //Assert.IsType<SuccessFlag>(response);
        }

        /// <summary>
        /// Test DeleteSheetRow
        /// </summary>
        [Fact]
        public void DeleteSheetRowTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //int rowIndex = null;
            //string? accountId = null;
            //string? xWorkspaceID = null;
            //var response = instance.DeleteSheetRow(id, rowIndex, accountId, xWorkspaceID);
            //Assert.IsType<SuccessFlag>(response);
        }

        /// <summary>
        /// Test GetSheet
        /// </summary>
        [Fact]
        public void GetSheetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //string? accountId = null;
            //string? xWorkspaceID = null;
            //var response = instance.GetSheet(id, accountId, xWorkspaceID);
            //Assert.IsType<Sheet>(response);
        }

        /// <summary>
        /// Test ListSheetRows
        /// </summary>
        [Fact]
        public void ListSheetRowsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //string? accountId = null;
            //string? xWorkspaceID = null;
            //int? limit = null;
            //int? offset = null;
            //var response = instance.ListSheetRows(id, accountId, xWorkspaceID, limit, offset);
            //Assert.IsType<RowList>(response);
        }

        /// <summary>
        /// Test ListSheets
        /// </summary>
        [Fact]
        public void ListSheetsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string? accountId = null;
            //string? provider = null;
            //string? xWorkspaceID = null;
            //int? limit = null;
            //int? offset = null;
            //var response = instance.ListSheets(accountId, provider, xWorkspaceID, limit, offset);
            //Assert.IsType<SheetListEnvelope>(response);
        }

        /// <summary>
        /// Test UpdateSheet
        /// </summary>
        [Fact]
        public void UpdateSheetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //UpdateSheetRequest updateSheetRequest = null;
            //string? accountId = null;
            //string? xWorkspaceID = null;
            //var response = instance.UpdateSheet(id, updateSheetRequest, accountId, xWorkspaceID);
            //Assert.IsType<Sheet>(response);
        }

        /// <summary>
        /// Test UpdateSheetCell
        /// </summary>
        [Fact]
        public void UpdateSheetCellTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //int rowIndex = null;
            //string column = null;
            //UpdateCellRequest updateCellRequest = null;
            //string? accountId = null;
            //string? xWorkspaceID = null;
            //var response = instance.UpdateSheetCell(id, rowIndex, column, updateCellRequest, accountId, xWorkspaceID);
            //Assert.IsType<Cell>(response);
        }

        /// <summary>
        /// Test UpdateSheetRow
        /// </summary>
        [Fact]
        public void UpdateSheetRowTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //int rowIndex = null;
            //UpdateRowRequest updateRowRequest = null;
            //string? accountId = null;
            //string? xWorkspaceID = null;
            //var response = instance.UpdateSheetRow(id, rowIndex, updateRowRequest, accountId, xWorkspaceID);
            //Assert.IsType<Row>(response);
        }
    }
}
